// app/src/data.js

export const CATEGORIES = {
  apps: {
    label: "Mac Apps",
    icon: "globe",
    subcategories: {
      desarrollo: "Desarrollo",
      utilidades: "Utilidades",
      browsers: "Browsers",
      comunicacion: "Comunicacion",
      seguridad: "Seguridad",
    },
  },
  cli: {
    label: "CLI Tools",
    icon: "terminal",
    subcategories: {
      "ai-agents": "AI Coding Agents",
      "browser-automation": "Browser & Automation",
      "dev-tools": "Dev Tools",
      "package-managers": "Package Managers & Deploy",
      "terminal-tools": "Terminal Tools",
    },
  },
  shell: {
    label: "Shell Setup",
    icon: "chevron-right",
    subcategories: {
      shell: "Shell",
    },
  },
  "claude-code": {
    label: "Claude Code",
    icon: "zap",
    subcategories: {
      plugins: "Plugins",
      skills: "Skills",
      agents: "Agents",
      commands: "Commands",
    },
  },
  extensions: {
    label: "VS Code Extensions",
    icon: "package",
    subcategories: {
      extensions: "Extensions",
    },
  },
};

export const items = [
  // === Mac Apps: Desarrollo ===
  {
    id: "cursor",
    name: "Cursor",
    category: "apps",
    subcategory: "desarrollo",
    description: "Editor de codigo con AI integrado (Claude, GPT). Basado en VS Code.",
    install: "brew install --cask cursor",
    installMethod: "brew",
    cost: "freemium",
    tags: ["editor", "ai", "vscode"],
    url: "https://cursor.com",
    related: ["vscode", "claude-code"],
    why: "Mi editor principal. La integracion con Claude es brutal para pair programming con AI.",
  },
  {
    id: "claude-desktop",
    name: "Claude Desktop",
    category: "apps",
    subcategory: "desarrollo",
    description: "App de escritorio de Claude. Chat + Claude Code integrado.",
    install: "brew install --cask claude",
    installMethod: "brew",
    cost: "freemium",
    tags: ["ai", "chat", "claude"],
    url: "https://claude.ai",
    related: ["claude-code-cli", "cursor"],
    why: "La uso para tareas de chat rapido y proyectos que no requieren la CLI. Tener Claude nativo en el escritorio cambia el workflow.",
  },
  {
    id: "docker",
    name: "Docker Desktop",
    category: "apps",
    subcategory: "desarrollo",
    description: "Contenedores para ejecutar apps aisladas y dev environments.",
    install: "brew install --cask docker",
    installMethod: "brew",
    cost: "free",
    tags: ["containers", "devops"],
    url: "https://docker.com",
    related: [],
    why: "Indispensable para levantar cualquier stack local sin contaminar el sistema. Sin Docker no trabajo.",
  },
  {
    id: "datagrip",
    name: "DataGrip",
    category: "apps",
    subcategory: "desarrollo",
    description: "IDE de JetBrains para bases de datos. SQL, PostgreSQL, Redis.",
    install: "brew install --cask datagrip",
    installMethod: "brew",
    cost: "paid",
    tags: ["database", "sql", "jetbrains"],
    url: "https://www.jetbrains.com/datagrip/",
    related: [],
    why: "El mejor cliente de DB que existe. El autocompletado de SQL y el diagrama de esquema me ahorran horas por semana.",
  },
  {
    id: "postman",
    name: "Postman",
    category: "apps",
    subcategory: "desarrollo",
    description: "Testing y documentacion de APIs. Collections, environments.",
    install: "brew install --cask postman",
    installMethod: "brew",
    cost: "free",
    tags: ["api", "testing"],
    url: "https://postman.com",
    related: [],
    why: "Para probar endpoints rapido y guardar collections de APIs del proyecto. No hay alternativa que se le acerque.",
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    category: "apps",
    subcategory: "desarrollo",
    description: "Editor de codigo open source de Microsoft. Extensions marketplace.",
    install: "brew install --cask visual-studio-code",
    installMethod: "brew",
    cost: "free",
    tags: ["editor", "microsoft"],
    url: "https://code.visualstudio.com",
    related: ["cursor"],
    why: "El fallback cuando necesito abrir algo rapido o cuando Cursor no es necesario. El ecosistema de extensions es imbatible.",
  },
  {
    id: "xcode",
    name: "Xcode",
    category: "apps",
    subcategory: "desarrollo",
    description: "IDE de Apple para desarrollo iOS/macOS.",
    install: "App Store",
    installMethod: "manual",
    cost: "free",
    tags: ["ios", "macos", "apple"],
    url: "https://developer.apple.com/xcode/",
    related: [],
    why: "Obligatorio si tocas algo de Apple. No me entusiasma, pero sin el simulador de iOS no puedo probar nada.",
  },
  {
    id: "neo4j",
    name: "Neo4j Desktop",
    category: "apps",
    subcategory: "desarrollo",
    description: "Gestion de bases de datos de grafos Neo4j.",
    install: "Download from neo4j.com",
    installMethod: "manual",
    cost: "free",
    tags: ["database", "graph"],
    url: "https://neo4j.com",
    related: ["datagrip"],
    why: "Para explorar grafos de conocimiento y relaciones complejas. El browser visual de Neo4j hace que los datos de grafos cobren vida.",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    category: "apps",
    subcategory: "desarrollo",
    description: "Editor de notas en Markdown. Plugins, graph view, vault local.",
    install: "brew install --cask obsidian",
    installMethod: "brew",
    cost: "free",
    tags: ["notes", "markdown"],
    url: "https://obsidian.md",
    related: [],
    why: "Mi segundo cerebro. Todo lo que aprendo va ahi. El graph view de links entre notas es adictivo y util de verdad.",
  },
  {
    id: "conductor",
    name: "Conductor",
    category: "apps",
    subcategory: "desarrollo",
    description: "Observabilidad y monitoreo de infraestructura.",
    install: "Enterprise install",
    installMethod: "manual",
    cost: "paid",
    tags: ["monitoring", "observability"],
    url: "",
    related: [],
    why: "Lo uso en el trabajo para monitorear pipelines en produccion. Cuando algo falla a las 2am, es lo primero que abro.",
  },
  // === Mac Apps: Utilidades ===
  {
    id: "alttab",
    name: "AltTab",
    category: "apps",
    subcategory: "utilidades",
    description: "Window switcher estilo Windows con preview de ventanas.",
    install: "brew install --cask alt-tab",
    installMethod: "brew",
    cost: "free",
    tags: ["windows", "productivity"],
    url: "https://alt-tab-macos.netlify.app",
    related: ["rectangle"],
    why: "El switcher nativo de Mac es una basura para multitasking serio. AltTab te da preview real de cada ventana como en Windows.",
  },
  {
    id: "rectangle",
    name: "Rectangle",
    category: "apps",
    subcategory: "utilidades",
    description: "Window management con atajos de teclado. Snapping y splits.",
    install: "brew install --cask rectangle",
    installMethod: "brew",
    cost: "free",
    tags: ["windows", "productivity"],
    url: "https://rectangleapp.com",
    related: ["alttab"],
    why: "No puedo vivir sin splits de terminal y editor en pantalla completa. Rectangle hace que Mac se comporte como deberia.",
  },
  {
    id: "betterdisplay",
    name: "BetterDisplay",
    category: "apps",
    subcategory: "utilidades",
    description: "Control avanzado de monitores. Resoluciones custom, brightness.",
    install: "brew install --cask betterdisplay",
    installMethod: "brew",
    cost: "freemium",
    tags: ["display", "monitor"],
    url: "https://betterdisplay.pro",
    related: [],
    why: "Para sacarle resoluciones custom al monitor externo sin que quede pixelado. Apple no da estas opciones de forma nativa.",
  },
  {
    id: "ice",
    name: "Ice",
    category: "apps",
    subcategory: "utilidades",
    description: "Menu bar manager. Oculta iconos para mantener la barra limpia.",
    install: "brew install --cask jordanbaird-ice",
    installMethod: "brew",
    cost: "free",
    tags: ["menubar", "productivity"],
    url: "https://icemenubar.app",
    related: ["stats"],
    why: "Con 20 apps abiertas la menu bar se convierte en un caos. Ice la mantiene limpia sin perder acceso a nada.",
  },
  {
    id: "stats",
    name: "Stats",
    category: "apps",
    subcategory: "utilidades",
    description: "Monitor del sistema en la menu bar. CPU, RAM, disco, red.",
    install: "brew install --cask stats",
    installMethod: "brew",
    cost: "free",
    tags: ["monitoring", "system"],
    url: "https://github.com/exelban/stats",
    related: ["htop", "ice"],
    why: "Un vistazo rapido a CPU y RAM sin abrir Activity Monitor. Cuando el fan arranca solo miro la barra y ya se que esta quemando.",
  },
  {
    id: "macs-fan-control",
    name: "Macs Fan Control",
    category: "apps",
    subcategory: "utilidades",
    description: "Control manual de ventiladores y monitoreo de temperatura.",
    install: "brew install --cask macs-fan-control",
    installMethod: "brew",
    cost: "freemium",
    tags: ["hardware", "temperature"],
    url: "https://crystalidea.com/macs-fan-control",
    related: ["stats"],
    why: "Cuando tengo modelos corriendo en local el Mac se convierte en una freidora. Esto me deja forzar el fan antes de que se queme.",
  },
  {
    id: "onyx",
    name: "OnyX",
    category: "apps",
    subcategory: "utilidades",
    description: "Mantenimiento y optimizacion de macOS. Limpieza de cache.",
    install: "brew install --cask onyx",
    installMethod: "brew",
    cost: "free",
    tags: ["maintenance", "macos"],
    url: "https://www.titanium-software.fr/en/onyx.html",
    related: [],
    why: "Lo corro cada par de meses para limpiar caches y mantener el sistema rapido. Una de esas cosas que no usas seguido pero cuando la necesitas vale oro.",
  },
  {
    id: "1password-cli",
    name: "1Password CLI",
    category: "apps",
    subcategory: "utilidades",
    description: "Acceso a passwords desde terminal. Secrets management.",
    install: "brew install --cask 1password-cli",
    installMethod: "brew",
    cost: "paid",
    tags: ["security", "passwords"],
    url: "https://1password.com",
    related: [],
    why: "Para inyectar secrets en scripts sin hardcodearlos. `op run` es una de las mejores integraciones de seguridad que existen para devs.",
  },
  {
    id: "cmux",
    name: "cmux",
    category: "apps",
    subcategory: "utilidades",
    description: "Multiplexor de sesiones Claude Code en paralelo.",
    install: "brew install --cask cmux",
    installMethod: "brew",
    cost: "free",
    tags: ["claude", "multiplexor"],
    url: "",
    related: ["claude-code-cli"],
    why: "Para correr multiples agentes de Claude Code en paralelo sin abrir 10 terminales. Multiplica la productividad cuando tenes tareas independientes.",
  },
  {
    id: "rightfont",
    name: "RightFont",
    category: "apps",
    subcategory: "utilidades",
    description: "Gestor de fuentes para macOS. Preview, activacion, organizacion.",
    install: "Manual download",
    installMethod: "manual",
    cost: "freemium",
    tags: ["fonts", "design"],
    url: "https://rightfontapp.com",
    related: [],
    why: "Tengo cientos de fuentes instaladas y sin un gestor decente es un caos. RightFont me deja activarlas on-demand sin relentizar el sistema.",
  },
  // === Mac Apps: Browsers ===
  {
    id: "brave",
    name: "Brave Browser",
    category: "apps",
    subcategory: "browsers",
    description: "Browser con bloqueo de ads y trackers integrado.",
    install: "brew install --cask brave-browser",
    installMethod: "brew",
    cost: "free",
    tags: ["browser", "privacy"],
    url: "https://brave.com",
    related: ["chrome"],
    why: "Mi browser principal. Sin ads nativos y mucho mas rapido que Chrome en sitios pesados. La privacidad es un bonus.",
  },
  {
    id: "chrome",
    name: "Google Chrome",
    category: "apps",
    subcategory: "browsers",
    description: "Browser de Google. Sync, extensions, DevTools.",
    install: "brew install --cask google-chrome",
    installMethod: "brew",
    cost: "free",
    tags: ["browser", "google"],
    url: "https://www.google.com/chrome/",
    related: ["brave"],
    why: "Lo tengo por los DevTools y para testing cross-browser. Cuando el cliente usa Chrome necesito reproducir exactamente su entorno.",
  },
  // === Mac Apps: Comunicacion ===
  {
    id: "slack",
    name: "Slack",
    category: "apps",
    subcategory: "comunicacion",
    description: "Mensajeria para equipos. Canales, threads, integraciones.",
    install: "brew install --cask slack",
    installMethod: "brew",
    cost: "free",
    tags: ["communication", "team"],
    url: "https://slack.com",
    related: [],
    why: "El estandar de facto en equipos tech. No me gusta mucho pero todos estan ahi, asi que no hay opcion.",
  },
  {
    id: "beeper",
    name: "Beeper",
    category: "apps",
    subcategory: "comunicacion",
    description: "Mensajeria unificada. iMessage, WhatsApp, Telegram, Discord en una app.",
    install: "Download from beeper.com",
    installMethod: "manual",
    cost: "free",
    tags: ["messaging", "unified"],
    url: "https://beeper.com",
    related: ["slack"],
    why: "Tener iMessage, WhatsApp y Telegram en una sola ventana es un game changer para el foco. Menos cambios de contexto = mas productividad.",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "apps",
    subcategory: "comunicacion",
    description: "Streaming de musica y podcasts.",
    install: "brew install --cask spotify",
    installMethod: "brew",
    cost: "freemium",
    tags: ["music", "streaming"],
    url: "https://spotify.com",
    related: [],
    why: "No codifico sin musica. Playlists de lo-fi y electronic para entrar en flow. El algoritmo de discovery es bastante bueno.",
  },
  // === Mac Apps: Seguridad ===
  {
    id: "cloudflare-warp",
    name: "Cloudflare WARP",
    category: "apps",
    subcategory: "seguridad",
    description: "VPN y DNS seguro. Encripta trafico de red.",
    install: "brew install --cask cloudflare-warp",
    installMethod: "brew",
    cost: "free",
    tags: ["vpn", "security", "dns"],
    url: "https://1.1.1.1",
    related: [],
    why: "DNS rapido y encriptado sin la complejidad de una VPN corporativa. Lo activo en redes publicas sin pensarlo dos veces.",
  },
  {
    id: "drata",
    name: "Drata Agent",
    category: "apps",
    subcategory: "seguridad",
    description: "Agente de compliance (SOC2, ISO). Monitorea configuracion de seguridad.",
    install: "Enterprise install",
    installMethod: "manual",
    cost: "paid",
    tags: ["compliance", "security"],
    url: "https://drata.com",
    related: [],
    why: "Requerimiento de la empresa para SOC2. No lo instale por gusto pero hace el compliance automatico en segundo plano sin molestar.",
  },
  // === CLI: AI Coding Agents ===
  {
    id: "claude-code-cli",
    name: "Claude Code",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Claude Code. Coding agent en terminal.",
    install: "pnpm install -g @anthropic-ai/claude-code",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding", "claude"],
    url: "https://docs.anthropic.com/en/docs/claude-code",
    related: ["gemini-cli", "codex-cli"],
    why: "El mejor coding agent que existe hoy. Lo uso para casi todo: refactors, debugging, PRs. Ha reemplazado el 70% de mi tiempo de coding manual.",
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI oficial de Google Gemini. Coding agent en terminal.",
    install: "pnpm install -g @google/gemini-cli",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding", "google"],
    url: "https://github.com/google-gemini/gemini-cli",
    related: ["claude-code-cli", "codex-cli"],
    why: "Lo tengo para benchmarks y para tareas donde el contexto largo de Gemini importa. Util para comparar resultados con Claude Code.",
  },
  {
    id: "codex-cli",
    name: "OpenAI Codex",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de OpenAI. Coding agent en terminal.",
    install: "pnpm install -g @openai/codex",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding", "openai"],
    url: "https://github.com/openai/codex",
    related: ["claude-code-cli", "gemini-cli"],
    why: "Alternativa a Claude Code para proyectos donde el cliente es fan de OpenAI. Lo mantengo instalado para no tener sorpresas.",
  },
  {
    id: "kilo-code",
    name: "Kilo Code",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Kilo Code. Coding agent en terminal.",
    install: "pnpm install -g @kilocode/cli",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding"],
    url: "",
    related: ["claude-code-cli"],
    why: "Lo estoy explorando como alternativa open-source a los agents principales. Prometedor para workflows que necesitan mas control.",
  },
  {
    id: "qwen-code",
    name: "Qwen Code",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Qwen para coding.",
    install: "pnpm install -g @qwen-code/qwen-code",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding"],
    url: "",
    related: ["claude-code-cli"],
    why: "Lo tengo para evaluar modelos chinos en tareas de codigo. Sorprendentemente competitivo en algunos benchmarks especificos.",
  },
  {
    id: "cubic-dev",
    name: "Cubic Dev AI",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Cubic Dev AI para coding.",
    install: "pnpm install -g @cubic-dev-ai/cli",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding"],
    url: "",
    related: ["claude-code-cli"],
    why: "En evaluacion. Lo probe por recomendacion de alguien del equipo. Todavia no lo he integrado al workflow diario pero pinta bien.",
  },
  {
    id: "probe",
    name: "Probe",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Probe Labs.",
    install: "pnpm install -g @probelabs/probe",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "search"],
    url: "",
    related: [],
    why: "Para busquedas semanticas en codigo. Cuando no recuerdo donde esta algo en un repo grande, Probe lo encuentra mejor que grep.",
  },
  // === CLI: Browser & Automation ===
  {
    id: "agent-browser",
    name: "agent-browser",
    category: "cli",
    subcategory: "browser-automation",
    description: "Browser automation CLI para AI agents.",
    install: "pnpm install -g agent-browser",
    installMethod: "pnpm",
    cost: "free",
    tags: ["browser", "automation"],
    url: "",
    related: [],
    why: "Para automatizar flujos web desde agentes AI sin levantar Playwright manual. Se integra directo con Claude Code.",
  },
  // === CLI: Dev Tools ===
  {
    id: "mint",
    name: "Mint",
    category: "cli",
    subcategory: "dev-tools",
    description: "CLI de Mint. Herramienta de desarrollo.",
    install: "pnpm install -g mint",
    installMethod: "pnpm",
    cost: "free",
    tags: ["dev"],
    url: "",
    related: [],
    why: "Parte del toolkit de dev general. Lo mantengo para proyectos especificos que dependen de el.",
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    category: "cli",
    subcategory: "dev-tools",
    description: "CLI de OpenClaw. Herramienta de desarrollo.",
    install: "pnpm install -g openclaw",
    installMethod: "pnpm",
    cost: "free",
    tags: ["dev"],
    url: "",
    related: [],
    why: "Herramienta de dev que probe y se quedo instalada. Util para ciertos tipos de analisis de repositorios.",
  },
  {
    id: "puzldai",
    name: "Puzld AI",
    category: "cli",
    subcategory: "dev-tools",
    description: "CLI de Puzld AI. Herramienta de desarrollo.",
    install: "pnpm install -g puzldai",
    installMethod: "pnpm",
    cost: "free",
    tags: ["dev", "ai"],
    url: "",
    related: [],
    why: "En exploracion. Tiene un enfoque interesante para razonar sobre codigo en pasos. Todavia evaluando si entra al toolkit definitivo.",
  },
  {
    id: "op-cli",
    name: "OP",
    category: "cli",
    subcategory: "dev-tools",
    description: "CLI de OP. Herramienta de desarrollo.",
    install: "pnpm install -g op",
    installMethod: "pnpm",
    cost: "free",
    tags: ["dev"],
    url: "",
    related: [],
    why: "Herramienta de dev para operaciones especificas del stack. Lo uso en scripts de automatizacion internos.",
  },
  // === CLI: Package Managers & Deploy ===
  {
    id: "pnpm",
    name: "pnpm",
    category: "cli",
    subcategory: "package-managers",
    description: "Package manager rapido y eficiente en disco.",
    install: "npm install -g pnpm",
    installMethod: "npm",
    cost: "free",
    tags: ["package-manager", "node"],
    url: "https://pnpm.io",
    related: ["uv"],
    why: "npm es lento y devora disco con node_modules duplicados. pnpm usa symlinks y es 2-3x mas rapido en installs. No vuelvo atras.",
  },
  {
    id: "uv",
    name: "uv",
    category: "cli",
    subcategory: "package-managers",
    description: "Python package manager ultra rapido. Escrito en Rust.",
    install: "curl -LsSf https://astral.sh/uv/install.sh | sh",
    installMethod: "curl",
    cost: "free",
    tags: ["package-manager", "python", "rust"],
    url: "https://docs.astral.sh/uv/",
    related: ["pnpm"],
    why: "pip es del siglo pasado. uv instala dependencias de Python en segundos, no minutos. Escrito en Rust, se nota.",
  },
  {
    id: "vercel-cli",
    name: "Vercel",
    category: "cli",
    subcategory: "package-managers",
    description: "CLI para deploy de apps web.",
    install: "pnpm install -g vercel",
    installMethod: "pnpm",
    cost: "freemium",
    tags: ["deploy", "hosting"],
    url: "https://vercel.com",
    related: [],
    why: "Deploy de frontend en segundos con `vercel`. Perfecto para probar cambios en produccion sin pipeline completo.",
  },
  // === CLI: Terminal Tools ===
  {
    id: "tmux",
    name: "tmux",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Multiplexor de terminal. Sesiones persistentes, splits.",
    install: "brew install tmux",
    installMethod: "brew",
    cost: "free",
    tags: ["terminal", "multiplexor"],
    url: "https://github.com/tmux/tmux",
    related: [],
    why: "No abro terminal sin tmux. Splits + sesiones persistentes = productividad. Si se cae la SSH, la sesion sigue viva.",
  },
  {
    id: "ripgrep",
    name: "ripgrep",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Busqueda de texto ultra rapida. Reemplaza grep.",
    install: "brew install ripgrep",
    installMethod: "brew",
    cost: "free",
    tags: ["search", "cli", "fast"],
    url: "https://github.com/BurntSushi/ripgrep",
    related: ["fzf"],
    why: "Reemplaza grep y es 10x mas rapido en repos grandes. Respeta .gitignore por defecto. No hay razon para usar grep.",
  },
  {
    id: "fzf",
    name: "fzf",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Fuzzy finder. Ctrl+R mejorado, busqueda de archivos.",
    install: "brew install fzf",
    installMethod: "brew",
    cost: "free",
    tags: ["search", "fuzzy", "terminal"],
    url: "https://github.com/junegunn/fzf",
    related: ["ripgrep"],
    why: "Ctrl+R sin fzf es como buscar en Google sin autocompletado. Tambien lo uso para seleccionar branches y archivos en pipelines.",
  },
  {
    id: "htop",
    name: "htop",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Monitor de procesos interactivo. Mejor que top.",
    install: "brew install htop",
    installMethod: "brew",
    cost: "free",
    tags: ["monitoring", "processes"],
    url: "https://htop.dev",
    related: ["stats", "aitop"],
    why: "Para ver que proceso esta comiendo CPU sin salir de la terminal. Mucho mas legible que top.",
  },
  {
    id: "aitop",
    name: "aitop",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Monitor del sistema con AI. Top-like con analisis inteligente.",
    install: "brew install aitop",
    installMethod: "brew",
    cost: "free",
    tags: ["monitoring", "ai"],
    url: "",
    related: ["htop"],
    why: "Lo probé porque la combinacion de AI + monitoreo me parecio curiosa. Util cuando queres que te explique por que algo esta lento.",
  },
  {
    id: "ffmpeg",
    name: "ffmpeg",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Procesamiento de audio/video. Conversion, encoding.",
    install: "brew install ffmpeg",
    installMethod: "brew",
    cost: "free",
    tags: ["media", "video", "audio"],
    url: "https://ffmpeg.org",
    related: [],
    why: "Para convertir videos de demos, recortar screencasts y comprimir grabaciones antes de compartir. Un one-liner reemplaza cualquier app GUI.",
  },
  {
    id: "ncdu",
    name: "ncdu",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Analizador de uso de disco con interfaz ncurses.",
    install: "brew install ncdu",
    installMethod: "brew",
    cost: "free",
    tags: ["disk", "storage"],
    url: "https://dev.yorhel.nl/ncdu",
    related: [],
    why: "Cuando el disco esta lleno y no se que ocupa el espacio. ncdu me muestra exactamente donde esta el problema en segundos.",
  },
  {
    id: "gh",
    name: "gh",
    category: "cli",
    subcategory: "terminal-tools",
    description: "CLI oficial de GitHub. PRs, issues, repos desde terminal.",
    install: "brew install gh",
    installMethod: "brew",
    cost: "free",
    tags: ["github", "git"],
    url: "https://cli.github.com",
    related: [],
    why: "Para crear PRs y revisar issues sin salir de la terminal. Lo uso constantemente con Claude Code para el ciclo completo de PR.",
  },
  {
    id: "jq",
    name: "jq",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Procesador de JSON en linea de comandos.",
    install: "brew install jq",
    installMethod: "brew",
    cost: "free",
    tags: ["json", "parsing"],
    url: "https://jqlang.github.io/jq/",
    related: [],
    why: "Parsear respuestas de APIs en scripts sin escribir Python. `curl ... | jq '.data[]'` es magia pura.",
  },
  {
    id: "shellcheck",
    name: "shellcheck",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Linter para scripts shell. Encuentra bugs y problemas.",
    install: "brew install shellcheck",
    installMethod: "brew",
    cost: "free",
    tags: ["linter", "shell"],
    url: "https://www.shellcheck.net",
    related: [],
    why: "Los scripts bash son faciles de arruinar. shellcheck atrapa los errores clasicos antes de que los encuentres a las 3am en produccion.",
  },
  {
    id: "nvtop",
    name: "nvtop",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Monitor de GPU (similar a htop para GPUs).",
    install: "brew install nvtop",
    installMethod: "brew",
    cost: "free",
    tags: ["gpu", "monitoring"],
    url: "https://github.com/Syllo/nvtop",
    related: ["htop"],
    why: "Para monitorear VRAM y carga de GPU cuando entreno modelos localmente. El equivalente de htop pero para GPUs.",
  },
  {
    id: "deno",
    name: "Deno",
    category: "cli",
    subcategory: "dev-tools",
    description: "Runtime de JS/TS con seguridad por defecto. Alternativa moderna a Node.",
    install: "brew install deno",
    installMethod: "brew",
    cost: "free",
    tags: ["runtime", "javascript", "typescript"],
    url: "https://deno.com",
    related: ["pnpm"],
    why: "Lo uso para scripts rapidos de TS sin config. Viene con formatter, linter y test runner built-in.",
  },
  {
    id: "go",
    name: "Go",
    category: "cli",
    subcategory: "dev-tools",
    description: "Lenguaje compilado de Google. Concurrente, tipado, rapido.",
    install: "brew install go",
    installMethod: "brew",
    cost: "free",
    tags: ["language", "compiled", "concurrency"],
    url: "https://go.dev",
    related: ["deno"],
    why: "Necesario para compilar herramientas como mole y rtk. Tambien lo uso para CLIs rapidos.",
  },
  {
    id: "rtk",
    name: "RTK (Rust Token Killer)",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Proxy CLI que ahorra 60-90% de tokens en operaciones de dev.",
    install: "brew install rtk",
    installMethod: "brew",
    cost: "free",
    tags: ["cli", "tokens", "proxy", "optimization"],
    url: "https://github.com/nicholasgasior/rtk",
    related: ["claude-code-cli"],
    why: "Reduce drasticamente el consumo de tokens en Claude Code. Se interpone como proxy en git, ls, etc. Imprescindible.",
  },
  {
    id: "bats-core",
    name: "bats-core",
    category: "cli",
    subcategory: "dev-tools",
    description: "Framework de testing para scripts Bash.",
    install: "brew install bats-core",
    installMethod: "brew",
    cost: "free",
    tags: ["testing", "bash", "shell"],
    url: "https://github.com/bats-core/bats-core",
    related: ["shellcheck"],
    why: "Para testear scripts de shell de forma automatizada. Lo uso con shellcheck para CI de scripts.",
  },
  {
    id: "sox",
    name: "sox",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Procesamiento de audio en linea de comandos. Grabacion, conversion, efectos.",
    install: "brew install sox",
    installMethod: "brew",
    cost: "free",
    tags: ["audio", "processing", "cli"],
    url: "https://sox.sourceforge.net",
    related: ["ffmpeg"],
    why: "El ffmpeg del audio. Lo uso para procesar grabaciones y convertir formatos desde la terminal.",
  },
  {
    id: "tectonic",
    name: "tectonic",
    category: "cli",
    subcategory: "dev-tools",
    description: "Compilador de LaTeX moderno. Descarga paquetes automaticamente.",
    install: "brew install tectonic",
    installMethod: "brew",
    cost: "free",
    tags: ["latex", "documents", "pdf"],
    url: "https://tectonic-typesetting.github.io",
    related: [],
    why: "Compila LaTeX sin necesitar una instalacion completa de TeX. Perfecto para papers y documentos academicos.",
  },
  {
    id: "mole",
    name: "mole",
    category: "cli",
    subcategory: "terminal-tools",
    description: "SSH tunneling simplificado. Crea tunnels con un comando.",
    install: "brew install mole",
    installMethod: "brew",
    cost: "free",
    tags: ["ssh", "tunneling", "networking"],
    url: "https://github.com/davrodpin/mole",
    related: [],
    why: "Hace SSH tunneling trivial. Un comando y tienes acceso a la DB de staging desde localhost.",
  },
  {
    id: "postgresql",
    name: "PostgreSQL 15",
    category: "cli",
    subcategory: "dev-tools",
    description: "Base de datos relacional. El estandar de la industria.",
    install: "brew install postgresql@15",
    installMethod: "brew",
    cost: "free",
    tags: ["database", "sql", "relational"],
    url: "https://www.postgresql.org",
    related: ["redis"],
    why: "Mi base de datos por defecto para cualquier proyecto serio. Con pgvector para embeddings es imbatible.",
  },
  {
    id: "redis",
    name: "Redis",
    category: "cli",
    subcategory: "dev-tools",
    description: "Base de datos in-memory. Cache, queues, pub/sub.",
    install: "brew install redis",
    installMethod: "brew",
    cost: "free",
    tags: ["database", "cache", "in-memory"],
    url: "https://redis.io",
    related: ["postgresql"],
    why: "Cache y queues. Lo uso para rate limiting, sesiones, y como broker de mensajes entre servicios.",
  },
  // === Shell Setup ===
  {
    id: "oh-my-zsh",
    name: "Oh My Zsh",
    category: "shell",
    subcategory: "shell",
    description: "Framework para Zsh. Aliases, plugins, themes. La base de todo.",
    install: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
    installMethod: "curl",
    cost: "free",
    tags: ["shell", "zsh", "framework"],
    url: "https://ohmyz.sh",
    related: ["powerlevel10k", "zsh-autosuggestions"],
    why: "La base de mi shell setup. Sin Oh My Zsh mi terminal se siente desnuda. Los aliases y plugins vienen solos.",
  },
  {
    id: "powerlevel10k",
    name: "Powerlevel10k",
    category: "shell",
    subcategory: "shell",
    description: "Theme ultra rapido con prompt customizable y iconos.",
    install: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k",
    installMethod: "git",
    cost: "free",
    tags: ["shell", "theme", "prompt"],
    url: "https://github.com/romkatv/powerlevel10k",
    related: ["oh-my-zsh"],
    why: "El prompt mas rapido y customizable que existe. Ver el git branch, estado de uv y tiempo de ejecucion en el prompt cambia la vida.",
  },
  {
    id: "zsh-autosuggestions",
    name: "zsh-autosuggestions",
    category: "shell",
    subcategory: "shell",
    description: "Sugiere comandos del historial mientras escribes.",
    install: "brew install zsh-autosuggestions",
    installMethod: "brew",
    cost: "free",
    tags: ["shell", "zsh", "productivity"],
    url: "https://github.com/zsh-users/zsh-autosuggestions",
    related: ["oh-my-zsh", "fzf"],
    why: "Autocompletado de comandos del historial en tiempo real. Escribo las primeras letras y presiono la flecha. No vuelvo a una shell sin esto.",
  },
  {
    id: "fzf-shell",
    name: "fzf (shell integration)",
    category: "shell",
    subcategory: "shell",
    description: "Fuzzy finder integrado en la shell. Ctrl+R mejorado.",
    install: "brew install fzf",
    installMethod: "brew",
    cost: "free",
    tags: ["shell", "search", "fuzzy"],
    url: "https://github.com/junegunn/fzf",
    related: ["oh-my-zsh", "ripgrep"],
    why: "Con la integracion en shell, Ctrl+R se convierte en un buscador fuzzy del historial. Nunca mas escribo comandos largos de memoria.",
  },
  // === Claude Code: Plugins ===
  {
    id: "plugin-context-mode",
    name: "context-mode",
    category: "claude-code",
    subcategory: "plugins",
    description: "Optimiza el context window ejecutando comandos en sandbox. Ahorra ~80% de tokens.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "optimization", "tokens"],
    url: "",
    related: ["plugin-superpowers"],
    why: "Lo construi para no quemar contexto en outputs largos. Ahorra ~80% de tokens reales en sesiones de trabajo intenso.",
  },
  {
    id: "plugin-code-simplifier",
    name: "code-simplifier",
    category: "claude-code",
    subcategory: "plugins",
    description: "Revisa codigo modificado para simplificar, mejorar calidad y encontrar issues.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "code-quality"],
    url: "",
    related: ["agent-code-simplifier"],
    why: "Lo configure para que Claude revise automaticamente el codigo que genera. Es como tener un code reviewer siempre activo.",
  },
  {
    id: "plugin-context7",
    name: "context7",
    category: "claude-code",
    subcategory: "plugins",
    description: "Context7 MCP server para busqueda de documentacion en tiempo real.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "docs", "search"],
    url: "",
    related: [],
    why: "Claude deja de alucinar APIs cuando tiene docs reales. Context7 inyecta documentacion actualizada al contexto automaticamente.",
  },
  {
    id: "plugin-frontend-design",
    name: "frontend-design",
    category: "claude-code",
    subcategory: "plugins",
    description: "Herramientas de disenio frontend: componentes, layouts, CSS.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "frontend", "design"],
    url: "",
    related: [],
    why: "Para construir componentes UI rapidamente con Claude. Le da contexto de disenio que mejora mucho la calidad del output visual.",
  },
  {
    id: "plugin-playwright",
    name: "playwright",
    category: "claude-code",
    subcategory: "plugins",
    description: "Browser automation via Playwright MCP. Testing, scraping, interaccion web.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "browser", "testing"],
    url: "",
    related: ["agent-browser"],
    why: "Le da ojos a Claude Code. Puede navegar, clickear y hacer screenshots sin que yo escriba una linea de Playwright.",
  },
  {
    id: "plugin-skill-creator",
    name: "skill-creator",
    category: "claude-code",
    subcategory: "plugins",
    description: "Crea, modifica y mide rendimiento de skills custom para Claude Code.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "skills"],
    url: "",
    related: [],
    why: "Lo uso para iterar en mis propios skills. Me permite medir si un skill nuevo realmente mejora los resultados antes de committear.",
  },
  {
    id: "plugin-superpowers",
    name: "superpowers",
    category: "claude-code",
    subcategory: "plugins",
    description: "Superpowers: writing-plans, executing-plans, brainstorming, systematic-debugging.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "workflow", "planning"],
    url: "",
    related: ["plugin-context-mode"],
    why: "El plugin mas importante del toolkit. Estructura el workflow de Claude en fases: plan, ejecutar, verificar. Sin el, Claude improvisa demasiado.",
  },
  {
    id: "plugin-claude-hud",
    name: "claude-hud",
    category: "claude-code",
    subcategory: "plugins",
    description: "HUD (Heads-Up Display) para Claude Code. Status line con info en tiempo real.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "ui", "monitoring"],
    url: "",
    related: [],
    why: "Ver tokens usados, costo de la sesion y status de herramientas en tiempo real. Antes lo corre a ciegas, ahora tengo datos.",
  },
  {
    id: "plugin-feature-dev",
    name: "feature-dev",
    category: "claude-code",
    subcategory: "plugins",
    description: "Asistente de desarrollo de features. Planificacion, implementacion, testing.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "development"],
    url: "",
    related: ["plugin-superpowers"],
    why: "Para features completas de principio a fin. Claude planifica, implementa y genera tests en un flujo cohesivo.",
  },
  {
    id: "plugin-claude-subconscious",
    name: "claude-subconscious",
    category: "claude-code",
    subcategory: "plugins",
    description: "Agente subconsciente de Letta AI. Memoria persistente entre sesiones.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "memory", "persistence"],
    url: "",
    related: [],
    why: "Para que Claude recuerde decisiones de arquitectura entre sesiones. Sin memoria persistente, hay que re-explicar el contexto cada vez.",
  },
  // === Claude Code: Skills ===
  {
    id: "skill-browser-automation",
    name: "/browser-automation",
    category: "claude-code",
    subcategory: "skills",
    description: "Browser automation CLI. Navegacion, forms, scraping, screenshots.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "browser", "automation"],
    url: "",
    related: ["agent-browser"],
    why: "Para automatizar cualquier tarea web sin escribir Playwright manual. Lo construi para scraping y testing de flujos de usuario.",
  },
  {
    id: "skill-cross-ai-debate",
    name: "/cross-ai-debate",
    category: "claude-code",
    subcategory: "skills",
    description: "Debate adversarial entre Claude Code, Codex CLI y Gemini CLI.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "ai", "debate"],
    url: "",
    related: [],
    why: "Lo construi para obtener perspectivas de multiples modelos en decisiones tecnicas. Cuando los tres coinciden, sabes que vas bien.",
  },
  {
    id: "skill-doc-sync",
    name: "/doc-sync",
    category: "claude-code",
    subcategory: "skills",
    description: "Auditoria y sincronizacion de CLAUDE.md y README.md. Detecta drift.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "docs"],
    url: "",
    related: ["skill-generate-readme"],
    why: "La documentacion siempre queda desfasada del codigo. Este skill audita y sincroniza automaticamente sin que yo tenga que recordarlo.",
  },
  {
    id: "skill-dream",
    name: "/dream",
    category: "claude-code",
    subcategory: "skills",
    description: "Consolidacion de memoria multi-fase. Merge updates, pruning.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "memory"],
    url: "",
    related: [],
    why: "Para consolidar y podar la memoria de Claude entre sesiones largas. Como un GC para el contexto acumulado.",
  },
  {
    id: "skill-electron",
    name: "/electron",
    category: "claude-code",
    subcategory: "skills",
    description: "Automatiza apps Electron (VS Code, Slack, Discord) via Chrome DevTools.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "electron", "automation"],
    url: "",
    related: ["skill-browser-automation"],
    why: "Acceso a apps Electron desde Claude. Puedo automatizar acciones en VS Code o Slack directamente desde el agente.",
  },
  {
    id: "skill-explore-app",
    name: "/explore-app",
    category: "claude-code",
    subcategory: "skills",
    description: "Exploracion sistematica de web apps. Reporte con screenshots.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "testing", "qa"],
    url: "",
    related: ["skill-test-and-fix"],
    why: "Para que Claude explore una app como un usuario real y genere un reporte con lo que encontro. Ideal para primeras revisiones de UI.",
  },
  {
    id: "skill-fastapi-standards",
    name: "/fastAPI-standards",
    category: "claude-code",
    subcategory: "skills",
    description: "Guia para construir/refactorizar pipelines FastAPI + Prefect + pgvector.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "fastapi", "python"],
    url: "",
    related: ["agent-architecture-reference"],
    why: "Mis estandares de arquitectura FastAPI codificados como skill. Claude sigue mis patrones sin que yo tenga que repetirlos cada sesion.",
  },
  {
    id: "skill-generate-readme",
    name: "/generate-readme",
    category: "claude-code",
    subcategory: "skills",
    description: "Genera README preciso analizando el codigo fuente del proyecto.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "docs"],
    url: "",
    related: ["skill-doc-sync"],
    why: "Nunca mas escribir READMEs a mano. Claude analiza el codigo real y genera documentacion precisa. Cero alucinaciones.",
  },
  {
    id: "skill-health",
    name: "/health",
    category: "claude-code",
    subcategory: "skills",
    description: "Diagnostico cuando Claude se siente lento o ignora reglas. Audita hooks y MCP.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "diagnostics"],
    url: "",
    related: [],
    why: "Lo construi para cuando Claude empieza a portarse raro. Diagnostica hooks, MCPs y configuracion en un solo comando.",
  },
  {
    id: "skill-pipeline-review",
    name: "/pipeline-review",
    category: "claude-code",
    subcategory: "skills",
    description: "Auditoria full-stack de codigo de pipelines. Agentes paralelos.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "review", "pipeline"],
    url: "",
    related: ["skill-review-plan-engineering"],
    why: "Para auditorias completas de pipelines de datos antes de deployar. Corre agentes en paralelo y consolida los hallazgos.",
  },
  {
    id: "skill-pre-merge-review",
    name: "/pre-merge-review",
    category: "claude-code",
    subcategory: "skills",
    description: "Review pre-landing de PRs. SQL safety, trust boundaries, side effects.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "review", "pr"],
    url: "",
    related: ["skill-ship-pr"],
    why: "El ultimo chequeo antes de mergear. SQL safety, secrets, side effects. Ha atrapado bugs reales que el review humano perdio.",
  },
  {
    id: "skill-project-docs",
    name: "/project-docs",
    category: "claude-code",
    subcategory: "skills",
    description: "Genera vambe.md y db.md como referencia de contexto para AI.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "docs"],
    url: "",
    related: ["skill-generate-readme"],
    why: "Genera documentos de contexto especificos para AI. Cuando cambio de proyecto Claude tiene todo lo que necesita sin que yo explique nada.",
  },
  {
    id: "skill-refactor-analysis",
    name: "/refactor-analysis",
    category: "claude-code",
    subcategory: "skills",
    description: "Analiza tech debt antes de refactorizar. Identifica code smells.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "refactoring"],
    url: "",
    related: [],
    why: "Antes de tocar codigo legacy, este skill mapea el tech debt real. Evita refactors que crean mas problemas de los que resuelven.",
  },
  {
    id: "skill-review-plan",
    name: "/review-plan-engineering",
    category: "claude-code",
    subcategory: "skills",
    description: "Review de planes de ingenieria. Arquitectura, data flow, tests.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "review", "planning"],
    url: "",
    related: ["skill-pipeline-review"],
    why: "Para revisar planes tecnicos antes de implementar. Detecta problemas de arquitectura en papel, no en produccion.",
  },
  {
    id: "skill-setup-browser-cookies",
    name: "/setup-browser-cookies",
    category: "claude-code",
    subcategory: "skills",
    description: "Importa cookies de tu browser real al headless para testing autenticado.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "browser", "auth"],
    url: "",
    related: ["skill-browser-automation"],
    why: "Para hacer testing automatizado en apps que requieren autenticacion real. Sin esto el browser headless no puede pasar el login.",
  },
  {
    id: "skill-ship-pr",
    name: "/ship-pr",
    category: "claude-code",
    subcategory: "skills",
    description: "Workflow de PR: merge main, tests, review diff, bump VERSION, changelog, commit, push, crear PR.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "git", "pr"],
    url: "",
    related: ["skill-pre-merge-review"],
    why: "El ritual completo de PR en un comando. Merge, tests, changelog, PR. Lo que antes me tomaba 15 minutos ahora tarda 2.",
  },
  {
    id: "skill-slack",
    name: "/slack",
    category: "claude-code",
    subcategory: "skills",
    description: "Interactua con workspaces Slack via browser automation.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "slack"],
    url: "",
    related: ["slack"],
    why: "Para que Claude pueda postear updates o buscar informacion en Slack sin que yo tenga que cambiar de contexto.",
  },
  {
    id: "skill-test-and-fix",
    name: "/test-and-fix",
    category: "claude-code",
    subcategory: "skills",
    description: "QA testing sistematico de web apps. Modos: diff-aware, full, quick, regression.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "testing", "qa"],
    url: "",
    related: ["skill-explore-app"],
    why: "Mi skill de QA mas usado. Encuentra y repara bugs en web apps automaticamente. El modo diff-aware es especialmente inteligente.",
  },
  {
    id: "skill-vercel-sandbox",
    name: "/vercel-sandbox",
    category: "claude-code",
    subcategory: "skills",
    description: "Browser automation en Vercel Sandbox microVMs. Chrome headless.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "vercel", "browser"],
    url: "",
    related: ["vercel-cli"],
    why: "Para testing en entornos Vercel aislados sin tocar produccion. Chrome headless en microVMs es sorprendentemente util.",
  },
  {
    id: "skill-weekly-retro",
    name: "/weekly-retro",
    category: "claude-code",
    subcategory: "skills",
    description: "Retrospectiva semanal de ingenieria. Analiza commits, metricas por persona.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "retro", "analytics"],
    url: "",
    related: [],
    why: "Para las retros del equipo. Claude analiza commits de la semana y genera metricas por persona. La data habla sola.",
  },
  {
    id: "skill-panel",
    name: "/panel",
    category: "claude-code",
    subcategory: "skills",
    description: "Panel de 3 lentes: simplificacion, arquitectura, producto. Multi-perspectiva.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "review", "decision"],
    url: "",
    related: ["agent-skeptical-reviewer"],
    why: "Para evaluar decisiones desde 3 angulos antes de comprometerse. Simplifica, revisa estructura, y valida producto en una sola pasada.",
  },
  {
    id: "skill-simplify",
    name: "/simplify",
    category: "claude-code",
    subcategory: "skills",
    description: "Revisa codigo cambiado para simplificar, mejorar calidad y eficiencia.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "code-quality", "refactor"],
    url: "",
    related: ["agent-code-simplifier"],
    why: "Lo corro despues de cada feature grande. Encuentra redundancia y complejidad innecesaria que se cuela cuando estas en modo rapido.",
  },
  {
    id: "skill-loop",
    name: "/loop",
    category: "claude-code",
    subcategory: "skills",
    description: "Ejecuta un prompt o slash command en intervalo recurrente.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "automation", "polling"],
    url: "",
    related: ["skill-schedule"],
    why: "Para monitorear deploys o procesos largos sin tener que volver a checkear manualmente. Set and forget.",
  },
  {
    id: "skill-schedule",
    name: "/schedule",
    category: "claude-code",
    subcategory: "skills",
    description: "Crea agentes remotos que ejecutan en cron schedule.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "automation", "cron"],
    url: "",
    related: ["skill-loop"],
    why: "Para tareas recurrentes que necesitan correr sin supervision. Reportes diarios, chequeos de salud, syncs automaticos.",
  },
  {
    id: "skill-claude-api",
    name: "/claude-api",
    category: "claude-code",
    subcategory: "skills",
    description: "Guia para construir apps con Claude API y Anthropic SDK.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "api", "sdk"],
    url: "",
    related: ["claude-code-cli"],
    why: "Se activa automaticamente cuando importas anthropic SDK. Asegura que uses las APIs correctas sin tener que buscar docs.",
  },
  // === Claude Code: Agents ===
  {
    id: "agent-tech-lead",
    name: "tech-lead",
    category: "claude-code",
    subcategory: "agents",
    description: "Decisiones tecnicas, coordinacion cross-domain.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "architecture"],
    url: "",
    related: ["agent-fullstack-refactor"],
    why: "El coordinador principal para decisiones que cruzan multiples dominios. Lo despachamos cuando la decision es demasiado grande para un solo agente.",
  },
  {
    id: "agent-fullstack-refactor",
    name: "fullstack-refactor-architect",
    category: "claude-code",
    subcategory: "agents",
    description: "Arquitectura, APIs, refactoring de monolitos.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "architecture"],
    url: "",
    related: ["agent-tech-lead"],
    why: "Para refactors grandes que tocan toda la arquitectura. Tiene el contexto suficiente para no romper contratos entre capas.",
  },
  {
    id: "agent-architecture-reference",
    name: "architecture-reference",
    category: "claude-code",
    subcategory: "agents",
    description: "Patrones de arquitectura para pipelines FastAPI.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "fastapi"],
    url: "",
    related: ["skill-fastapi-standards"],
    why: "Mis patrones de FastAPI encapsulados en un agente. Cuando el codigo se desvía de los estandares, este agente lo corrige.",
  },
  {
    id: "agent-db-engineering",
    name: "db-engineering",
    category: "claude-code",
    subcategory: "agents",
    description: "Schemas, queries, migraciones, indexing.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "database"],
    url: "",
    related: ["datagrip"],
    why: "Para todo lo que toca la DB. Genera migraciones, optimiza queries y revisa indexes sin que yo tenga que pensar en SQL edge cases.",
  },
  {
    id: "agent-code-modularizer",
    name: "code-modularizer",
    category: "claude-code",
    subcategory: "agents",
    description: "Romper archivos grandes, extraer duplicados.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "refactoring"],
    url: "",
    related: ["agent-code-simplifier"],
    why: "Cuando un archivo supera las 500 lineas, este agente lo parte en modulos coherentes sin romper los imports.",
  },
  {
    id: "agent-code-simplifier",
    name: "code-simplifier",
    category: "claude-code",
    subcategory: "agents",
    description: "Simplificar, refactorizar y limpiar codigo.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "refactoring"],
    url: "",
    related: ["agent-code-modularizer"],
    why: "Para eliminar complejidad innecesaria. Le paso codigo verboso y lo devuelve limpio sin perder funcionalidad.",
  },
  {
    id: "agent-skeptical-reviewer",
    name: "skeptical-reviewer",
    category: "claude-code",
    subcategory: "agents",
    description: "Devil's advocate. Desafia suposiciones antes de decidir.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "review"],
    url: "",
    related: [],
    why: "Para no enamorarme de mis propias ideas. Lo corro contra cada decision importante y siempre encuentra al menos un fallo que no vi.",
  },
  {
    id: "agent-ai-ml-expert",
    name: "ai-ml-expert",
    category: "claude-code",
    subcategory: "agents",
    description: "Prompts, RAG, embeddings, model selection.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "ai", "ml"],
    url: "",
    related: ["agent-ai-researcher"],
    why: "Para decisiones de arquitectura AI/ML: que modelo usar, como estructurar un RAG, que estrategia de embeddings. Mi experto interno.",
  },
  {
    id: "agent-ai-researcher",
    name: "ai-researcher",
    category: "claude-code",
    subcategory: "agents",
    description: "Papers, experimentos, metodologia, escritura cientifica.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "research"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "Para cuando necesito rigor cientifico en un analisis. Disenio de experimentos, revision de papers, metodologia solida.",
  },
  {
    id: "agent-prompt-engineering",
    name: "prompt-engineering",
    category: "claude-code",
    subcategory: "agents",
    description: "Craft y optimizar prompts para LLMs.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "prompts"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "Para iterar en prompts de manera sistematica. Analiza por que un prompt falla y sugiere variantes con razonamiento.",
  },
  {
    id: "agent-data-science",
    name: "data-science-analytics",
    category: "claude-code",
    subcategory: "agents",
    description: "EDA, estadisticas, visualizacion, ML.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "data"],
    url: "",
    related: [],
    why: "Para analisis exploratorios rapidos. Le paso un dataset y me da EDA completo con estadisticas y visualizaciones listas.",
  },
  {
    id: "agent-neuroscience",
    name: "neuroscience-ai-expert",
    category: "claude-code",
    subcategory: "agents",
    description: "Neurociencia, mecanismos neurales, brain-computer interfaces.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "neuroscience"],
    url: "",
    related: ["agent-neuroai-director"],
    why: "Para proyectos en la interseccion de AI y neurociencia. Tiene contexto profundo de mecanismos neurales que otros agentes no manejan.",
  },
  {
    id: "agent-neuroai-director",
    name: "neuroai-research-director",
    category: "claude-code",
    subcategory: "agents",
    description: "Metodologia de investigacion, NeuroAI, disenio de experimentos.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "research", "neuroscience"],
    url: "",
    related: ["agent-neuroscience"],
    why: "El director de investigacion virtual para proyectos NeuroAI. Garantiza que el disenio experimental sea solido antes de correr nada.",
  },
  {
    id: "agent-thesis-reviewer",
    name: "thesis-reviewer",
    category: "claude-code",
    subcategory: "agents",
    description: "Review de tesis, deteccion de texto AI, escritura academica.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "academic"],
    url: "",
    related: ["agent-ai-researcher"],
    why: "Para ayudar a revisar tesis de colegas y asegurar que el lenguaje academico sea correcto. Detecta tambien texto AI que suena raro.",
  },
  {
    id: "agent-ceo-strategist",
    name: "ceo-product-strategist",
    category: "claude-code",
    subcategory: "agents",
    description: "Vision estrategica CEO, roadmap, impacto de producto.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "strategy"],
    url: "",
    related: [],
    why: "Para pensar en impacto de producto mas alla del codigo. Util para preparar pitches y decidir que features priorizar con logica de negocio.",
  },
  {
    id: "agent-qa-test",
    name: "qa-test-engineer",
    category: "claude-code",
    subcategory: "agents",
    description: "Test strategies, edge cases, automation.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "testing"],
    url: "",
    related: ["skill-test-and-fix"],
    why: "Para disenar estrategias de testing completas. Encuentra edge cases que yo nunca consideraria y genera los tests automaticamente.",
  },
  {
    id: "agent-andrej-karpathy",
    name: "andrej-karpathy",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de Karpathy: implementaciones simples, first-principles, code review minimalista.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "ai", "persona"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "Para cuando necesito una opinion brutal sobre complejidad innecesaria. Karpathy siempre elige lo mas simple que funcione.",
  },
  {
    id: "agent-ilya-sutskever",
    name: "ilya-sutskever",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de Sutskever: scaling laws, safety, convicciones profundas sobre AI.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "ai", "persona"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "Para perspectivas sobre la trayectoria de AI, limites de scaling, y decisiones de safety. El oraculo del lab.",
  },
  {
    id: "agent-leonardo-da-vinci",
    name: "leonardo-da-vinci",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de Da Vinci: pensamiento polimata, patrones cross-domain, arte + ciencia.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "creativity", "persona"],
    url: "",
    related: [],
    why: "Para encontrar patrones entre dominios que ningun agente especializado ve. El polimata original aplicado a problemas modernos.",
  },
  {
    id: "agent-yann-lecun",
    name: "yann-lecun",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de LeCun: world models, critica contrarian, rigor cientifico combativo.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "ai", "persona"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "El contrarian que necesitas. Si tu idea sobrevive a LeCun, sobrevive a cualquiera. Anti-hype por defecto.",
  },
  {
    id: "agent-paul-graham",
    name: "paul-graham",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de PG: evaluacion de startups first-principles, escritura clara, contrarian product thinking.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "startup", "persona"],
    url: "",
    related: ["agent-ceo-strategist"],
    why: "Para evaluar honestamente si estoy construyendo algo que la gente realmente quiere. Y para feedback brutal sobre escritura.",
  },
  {
    id: "agent-steve-jobs",
    name: "steve-jobs",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de Jobs: vision de producto, obsesion por el diseno, simplicidad por sustraccion.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "product", "persona"],
    url: "",
    related: ["agent-ceo-strategist"],
    why: "Para evaluacion ruthless de producto. Cuando necesito que alguien me diga si vale la pena shipear o si hay que cortar features.",
  },
  {
    id: "agent-ops-impact",
    name: "ops-impact-analyst",
    category: "claude-code",
    subcategory: "agents",
    description: "ROI de features, metricas de negocio, reportes ejecutivos.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "business"],
    url: "",
    related: ["agent-ceo-strategist"],
    why: "Para conectar metricas tecnicas con impacto de negocio. Convierte 'mejoramos latencia 200ms' en 'ahorramos $X/mes'.",
  },
  {
    id: "agent-tw93",
    name: "tw93",
    category: "claude-code",
    subcategory: "agents",
    description: "Gatekeeper de Mole: minimalismo, safety-first, scope discipline.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "review"],
    url: "",
    related: ["agent-skeptical-reviewer"],
    why: "Simula al maintainer upstream de Mole para evaluar si un PR seria aceptado. Filtra scope creep antes de escribir codigo.",
  },
  {
    id: "agent-paul-graham",
    name: "Paul Graham",
    category: "claude-code",
    subcategory: "agents",
    description: "Piensa como Paul Graham: startups, simplicidad, growth, y ensayos claros.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "startup", "strategy"],
    url: "",
    related: ["agent-ceo-strategist", "agent-skeptical-reviewer"],
    why: "Para evaluar ideas de producto y estrategia con el mindset de YC. Corta la complejidad innecesaria y busca lo esencial.",
  },
  {
    id: "skill-sync-dotfiles",
    name: "Sync Dotfiles",
    category: "claude-code",
    subcategory: "skills",
    description: "Sincroniza config de la maquina al repo. Detecta herramientas nuevas, actualiza data.js y regenera docs.",
    install: "/sync-dotfiles",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "skill", "sync", "dotfiles"],
    url: "",
    related: [],
    why: "El inverso de setup.sh. Mantiene el repo actualizado con lo que realmente esta instalado. Single source of truth.",
  },
  {
    id: "skill-browser",
    name: "Browser (headless)",
    category: "claude-code",
    subcategory: "skills",
    description: "Headless browser para QA testing. Screenshots, navegacion, verificacion de estado.",
    install: "/browser",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "skill", "browser", "testing"],
    url: "",
    related: ["skill-browser-automation", "skill-explore-app"],
    why: "Version rapida de browser-automation. Para QA testing directo sin tanta ceremonia.",
  },
  // === Claude Code: Commands ===
  {
    id: "cmd-redesign-ui",
    name: "/redesign-ui",
    category: "claude-code",
    subcategory: "commands",
    description: "Analiza componentes UI y los redisena usando ui-designer y ux-designer en paralelo.",
    install: "Custom command",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "command", "ui"],
    url: "",
    related: [],
    why: "Lo construi para iterar en UI rapido. Dos agentes de disenio en paralelo y me quedo con la mejor propuesta. Ahorra horas de iteracion manual.",
  },
  {
    id: "cmd-python-review",
    name: "/python-review",
    category: "claude-code",
    subcategory: "commands",
    description: "Revisa codigo Python para calidad, seguridad, type safety y mejores practicas.",
    install: "Custom command",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "command", "python"],
    url: "",
    related: [],
    why: "Para revisar Python con mis propios estandares antes de mergear. Chequea type hints, seguridad y patrones que me importan a mi.",
  },
  {
    id: "cmd-security-scan",
    name: "/security-scan",
    category: "claude-code",
    subcategory: "commands",
    description: "Escaneo de seguridad. Busca vulnerabilidades, secretos hardcodeados, dependencias riesgosas.",
    install: "Custom command",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "command", "security"],
    url: "",
    related: [],
    why: "Lo corro antes de cualquier deploy publico. Ha encontrado secrets hardcodeados que pasaron el review humano mas de una vez.",
  },
  // === VS Code Extensions ===
  {
    id: "ext-claude-code",
    name: "Claude Code",
    category: "extensions",
    subcategory: "extensions",
    description: "Integracion de Claude Code en el editor.",
    install: "code --install-extension anthropic.claude-code",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "ai", "claude"],
    url: "",
    related: ["claude-code-cli"],
    why: "Para usar Claude Code directamente dentro del editor sin cambiar de ventana. La integracion con el diff view es excelente.",
  },
  {
    id: "ext-eslint",
    name: "ESLint",
    category: "extensions",
    subcategory: "extensions",
    description: "Linting de JavaScript/TypeScript.",
    install: "code --install-extension dbaeumer.vscode-eslint",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "linting", "javascript"],
    url: "",
    related: ["ext-prettier"],
    why: "Esencial para JS/TS. Sin ESLint el codigo del equipo diverge rapidamente en estilo y calidad.",
  },
  {
    id: "ext-gitlens",
    name: "GitLens",
    category: "extensions",
    subcategory: "extensions",
    description: "Git supercharged: blame, history, comparisons.",
    install: "code --install-extension eamodio.gitlens",
    installMethod: "vscode",
    cost: "freemium",
    tags: ["vscode", "git"],
    url: "",
    related: ["ext-git-graph"],
    why: "El inline blame me dice en segundos quien escribio cada linea y por que. Indispensable para entender codigo legacy.",
  },
  {
    id: "ext-prettier",
    name: "Prettier",
    category: "extensions",
    subcategory: "extensions",
    description: "Code formatter. JS, TS, CSS, HTML, JSON.",
    install: "code --install-extension esbenp.prettier-vscode",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "formatting"],
    url: "",
    related: ["ext-eslint", "ext-prettier-eslint"],
    why: "Format on save y nunca mas discutir estilos de codigo en PRs. Prettier cierra esas conversaciones para siempre.",
  },
  {
    id: "ext-git-ai",
    name: "Git AI",
    category: "extensions",
    subcategory: "extensions",
    description: "Integracion de git-ai en VS Code.",
    install: "code --install-extension git-ai.git-ai-vscode",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "git", "ai"],
    url: "",
    related: [],
    why: "Para generar commit messages automaticos con AI. Los commits descriptivos sin esfuerzo mental son un lujo que ya no quiero dejar.",
  },
  {
    id: "ext-copilot-chat",
    name: "GitHub Copilot Chat",
    category: "extensions",
    subcategory: "extensions",
    description: "Chat de GitHub Copilot en el editor.",
    install: "code --install-extension github.copilot-chat",
    installMethod: "vscode",
    cost: "freemium",
    tags: ["vscode", "ai", "copilot"],
    url: "",
    related: ["ext-claude-code"],
    why: "Alternativa a Claude Code para preguntas rapidas en el editor. Util cuando quiero una segunda opinion de un modelo diferente.",
  },
  {
    id: "ext-gitpod-theme",
    name: "Gitpod Theme",
    category: "extensions",
    subcategory: "extensions",
    description: "Color theme de Gitpod.",
    install: "code --install-extension gitpod.gitpod-theme",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "theme"],
    url: "",
    related: ["ext-material-icons"],
    why: "El tema oscuro con el que mejor me siento despues de probar docenas. Buen contraste y colores que no cansan la vista en sesiones largas.",
  },
  {
    id: "ext-material-icons",
    name: "Material Theme Icons",
    category: "extensions",
    subcategory: "extensions",
    description: "Iconos Material Design para archivos y carpetas.",
    install: "code --install-extension kd3n1z.vscode-material-theme-icons",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "icons", "theme"],
    url: "",
    related: ["ext-gitpod-theme"],
    why: "Los iconos hacen que el file explorer sea mucho mas escaneable. Diferenciar un .ts de un .tsx de un .json a golpe de vista importa.",
  },
  {
    id: "ext-rainbow-csv",
    name: "Rainbow CSV",
    category: "extensions",
    subcategory: "extensions",
    description: "Colorea columnas de CSV/TSV para lectura facil.",
    install: "code --install-extension mechatroner.rainbow-csv",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "csv"],
    url: "",
    related: [],
    why: "Trabajar con CSVs sin esto es sufrimiento puro. Colores por columna y los datos de golpe se vuelven legibles.",
  },
  {
    id: "ext-git-graph",
    name: "Git Graph",
    category: "extensions",
    subcategory: "extensions",
    description: "Visualizacion de grafos Git en VS Code.",
    install: "code --install-extension mhutchie.git-graph",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "git"],
    url: "",
    related: ["ext-gitlens"],
    why: "Para visualizar branches y merges sin salir del editor. Cuando el historial se complica, el grafo visual lo aclara todo.",
  },
  {
    id: "ext-python-debugger",
    name: "Python Debugger",
    category: "extensions",
    subcategory: "extensions",
    description: "Debugger para Python.",
    install: "code --install-extension ms-python.debugpy",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "python", "debug"],
    url: "",
    related: ["ext-python"],
    why: "Para debugging con breakpoints reales en Python. Los print statements son del pasado.",
  },
  {
    id: "ext-python",
    name: "Python",
    category: "extensions",
    subcategory: "extensions",
    description: "Soporte completo: IntelliSense, linting, formatting.",
    install: "code --install-extension ms-python.python",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "python"],
    url: "",
    related: ["ext-pylance", "ext-python-debugger"],
    why: "La extension base para cualquier proyecto Python. Sin esto el editor no sabe nada del lenguaje.",
  },
  {
    id: "ext-pylance",
    name: "Python Pylance",
    category: "extensions",
    subcategory: "extensions",
    description: "Language server de Python con type checking avanzado.",
    install: "code --install-extension ms-python.vscode-pylance",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "python"],
    url: "",
    related: ["ext-python"],
    why: "El type checking en tiempo real de Pylance ha prevenido mas bugs que cualquier suite de tests. Esencial para Python moderno.",
  },
  {
    id: "ext-python-envs",
    name: "Python Environments",
    category: "extensions",
    subcategory: "extensions",
    description: "Gestor de entornos Python en VS Code.",
    install: "code --install-extension ms-python.vscode-python-envs",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "python"],
    url: "",
    related: ["ext-python"],
    why: "Para cambiar entre virtualenvs sin tocar la terminal. Util cuando manejo multiples proyectos Python con dependencias diferentes.",
  },
  {
    id: "ext-jupyter",
    name: "Jupyter",
    category: "extensions",
    subcategory: "extensions",
    description: "Soporte para notebooks Jupyter en el editor.",
    install: "code --install-extension ms-toolsai.jupyter",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "jupyter", "notebooks"],
    url: "",
    related: ["ext-jupyter-keymap", "ext-jupyter-renderers"],
    why: "Para abrir y editar notebooks directamente en VS Code sin levantar el servidor Jupyter. El EDA se vuelve mucho mas fluido.",
  },
  {
    id: "ext-jupyter-keymap",
    name: "Jupyter Keymap",
    category: "extensions",
    subcategory: "extensions",
    description: "Atajos de teclado de Jupyter en VS Code.",
    install: "code --install-extension ms-toolsai.jupyter-keymap",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "jupyter"],
    url: "",
    related: ["ext-jupyter"],
    why: "Para no reaprender atajos al pasar de Jupyter browser a VS Code. La memoria muscular es importante.",
  },
  {
    id: "ext-jupyter-renderers",
    name: "Jupyter Renderers",
    category: "extensions",
    subcategory: "extensions",
    description: "Renderers adicionales para outputs de Jupyter.",
    install: "code --install-extension ms-toolsai.jupyter-renderers",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "jupyter"],
    url: "",
    related: ["ext-jupyter"],
    why: "Para visualizar plots y outputs complejos directamente en el notebook sin exportar nada.",
  },
  {
    id: "ext-jupyter-cell-tags",
    name: "Jupyter Cell Tags",
    category: "extensions",
    subcategory: "extensions",
    description: "Tags para celdas de Jupyter notebooks.",
    install: "code --install-extension ms-toolsai.vscode-jupyter-cell-tags",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "jupyter"],
    url: "",
    related: ["ext-jupyter"],
    why: "Para marcar celdas con tags y filtrarlas en exports. Util para separar celdas de analisis de las de presentacion.",
  },
  {
    id: "ext-jupyter-slideshow",
    name: "Jupyter Slideshow",
    category: "extensions",
    subcategory: "extensions",
    description: "Slideshow mode para Jupyter notebooks.",
    install: "code --install-extension ms-toolsai.vscode-jupyter-slideshow",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "jupyter"],
    url: "",
    related: ["ext-jupyter"],
    why: "Para convertir notebooks en presentaciones sin moverlos a otro formato. Util para demos tecnicas directamente desde el codigo.",
  },
  {
    id: "ext-prettier-eslint",
    name: "Prettier ESLint",
    category: "extensions",
    subcategory: "extensions",
    description: "Formatea con Prettier y aplica ESLint fixes.",
    install: "code --install-extension rvest.vs-code-prettier-eslint",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "formatting", "linting"],
    url: "",
    related: ["ext-prettier", "ext-eslint"],
    why: "Prettier y ESLint a veces se pelean. Esta extension los corre en el orden correcto para que no haya conflictos.",
  },
  {
    id: "ext-markdown-preview",
    name: "Markdown Preview Enhanced",
    category: "extensions",
    subcategory: "extensions",
    description: "Preview avanzado de Markdown con soporte LaTeX, diagrams.",
    install: "code --install-extension shd101wyy.markdown-preview-enhanced",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "markdown"],
    url: "",
    related: [],
    why: "Para escribir docs tecnicas con LaTeX y diagramas sin salir del editor. El preview en tiempo real es imprescindible.",
  },
];
