// app/src/data.js

export const CATEGORIES = {
  apps: {
    label: "Mac Apps",
    icon: "globe",
    subcategories: {
      desarrollo: "Desarrollo",
      utilidades: "Utilidades",
      browsers: "Browsers",
      comunicacion: "Comunicacion",
      seguridad: "Seguridad",
    },
  },
  cli: {
    label: "CLI Tools",
    icon: "terminal",
    subcategories: {
      "ai-agents": "AI Coding Agents",
      "browser-automation": "Browser & Automation",
      "dev-tools": "Dev Tools",
      "package-managers": "Package Managers & Deploy",
      "terminal-tools": "Terminal Tools",
    },
  },
  shell: {
    label: "Shell Setup",
    icon: "chevron-right",
    subcategories: {
      shell: "Shell",
    },
  },
  "claude-code": {
    label: "Claude Code",
    icon: "zap",
    subcategories: {
      plugins: "Plugins",
      skills: "Skills",
      agents: "Agents",
      commands: "Commands",
    },
  },
  extensions: {
    label: "VS Code Extensions",
    icon: "package",
    subcategories: {
      extensions: "Extensions",
    },
  },
};

export const items = [
  // === Mac Apps: Desarrollo ===
  {
    id: "claude-desktop",
    name: "Claude Desktop",
    category: "apps",
    subcategory: "desarrollo",
    description: "App de escritorio de Claude. Chat + Claude Code integrado.",
    install: "brew install --cask claude",
    installMethod: "manual",
    cost: "freemium",
    tags: ["ai", "chat", "claude"],
    url: "https://claude.ai",
    related: ["claude-code-cli"],
    why: "La uso para tareas de chat rapido y proyectos que no requieren la CLI. Tener Claude nativo en el escritorio cambia el workflow.",
  },
  {
    id: "docker",
    name: "Docker Desktop",
    category: "apps",
    subcategory: "desarrollo",
    description: "Contenedores para ejecutar apps aisladas y dev environments.",
    install: "brew install --cask docker",
    installMethod: "manual",
    cost: "free",
    tags: ["containers", "devops"],
    url: "https://docker.com",
    related: [],
    why: "Indispensable para levantar cualquier stack local sin contaminar el sistema. Sin Docker no trabajo.",
  },
  {
    id: "datagrip",
    name: "DataGrip",
    category: "apps",
    subcategory: "desarrollo",
    description: "IDE de JetBrains para bases de datos. SQL, PostgreSQL, Redis.",
    install: "brew install --cask datagrip",
    installMethod: "manual",
    cost: "paid",
    tags: ["database", "sql", "jetbrains"],
    url: "https://www.jetbrains.com/datagrip/",
    related: [],
    why: "El mejor cliente de DB que existe. El autocompletado de SQL y el diagrama de esquema me ahorran horas por semana.",
  },
  {
    id: "postman",
    name: "Postman",
    category: "apps",
    subcategory: "desarrollo",
    description: "Testing y documentacion de APIs. Collections, environments.",
    install: "brew install --cask postman",
    installMethod: "manual",
    cost: "free",
    tags: ["api", "testing"],
    url: "https://postman.com",
    related: [],
    why: "Para probar endpoints rapido y guardar collections de APIs del proyecto. No hay alternativa que se le acerque.",
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    category: "apps",
    subcategory: "desarrollo",
    description: "Editor de codigo open source de Microsoft. Extensions marketplace.",
    install: "brew install --cask visual-studio-code",
    installMethod: "brew",
    cost: "free",
    tags: ["editor", "microsoft"],
    url: "https://code.visualstudio.com",
    related: [],
    why: "Mi editor principal. El ecosistema de extensions es imbatible.",
  },
  {
    id: "xcode",
    name: "Xcode",
    category: "apps",
    subcategory: "desarrollo",
    description: "IDE de Apple para desarrollo iOS/macOS.",
    install: "App Store",
    installMethod: "manual",
    cost: "free",
    tags: ["ios", "macos", "apple"],
    url: "https://developer.apple.com/xcode/",
    related: [],
    why: "Obligatorio si tocas algo de Apple. No me entusiasma, pero sin el simulador de iOS no puedo probar nada.",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    category: "apps",
    subcategory: "desarrollo",
    description: "Editor de notas en Markdown. Plugins, graph view, vault local.",
    install: "brew install --cask obsidian",
    installMethod: "brew",
    cost: "free",
    tags: ["notes", "markdown"],
    url: "https://obsidian.md",
    related: [],
    why: "Mi segundo cerebro. Todo lo que aprendo va ahi. El graph view de links entre notas es adictivo y util de verdad.",
  },
  {
    id: "notion",
    name: "Notion",
    category: "apps",
    subcategory: "desarrollo",
    description: "Workspace todo-en-uno. Notas, docs, wikis, bases de datos, kanban.",
    install: "Download from notion.so",
    installMethod: "manual",
    cost: "freemium",
    tags: ["notes", "workspace", "docs"],
    url: "https://notion.so",
    related: ["obsidian"],
    why: "Para documentacion compartida del equipo. Obsidian es personal, Notion es el espacio colaborativo donde todos escriben.",
  },
  {
    id: "zotero",
    name: "Zotero",
    category: "apps",
    subcategory: "desarrollo",
    description: "Gestor de referencias bibliograficas. Papers, PDFs, citas.",
    install: "Download from zotero.org",
    installMethod: "manual",
    cost: "free",
    tags: ["academic", "references", "papers"],
    url: "https://www.zotero.org",
    related: [],
    why: "Para organizar papers y referencias academicas. Cuando investigo un tema nuevo, todos los PDFs y citas quedan en un solo lugar.",
  },
  {
    id: "conductor",
    name: "Conductor",
    category: "apps",
    subcategory: "desarrollo",
    description: "Observabilidad y monitoreo de infraestructura.",
    install: "Enterprise install",
    installMethod: "manual",
    cost: "paid",
    tags: ["monitoring", "observability"],
    url: "",
    related: [],
    why: "Lo uso en el trabajo para monitorear pipelines en produccion. Cuando algo falla a las 2am, es lo primero que abro.",
  },
  // === Mac Apps: Utilidades ===
  {
    id: "alttab",
    name: "AltTab",
    category: "apps",
    subcategory: "utilidades",
    description: "Window switcher estilo Windows con preview de ventanas.",
    install: "brew install --cask alt-tab",
    installMethod: "brew",
    cost: "free",
    tags: ["windows", "productivity"],
    url: "https://alt-tab-macos.netlify.app",
    related: ["rectangle"],
    why: "El switcher nativo de Mac es una basura para multitasking serio. AltTab te da preview real de cada ventana como en Windows.",
  },
  {
    id: "rectangle",
    name: "Rectangle",
    category: "apps",
    subcategory: "utilidades",
    description: "Window management con atajos de teclado. Snapping y splits.",
    install: "brew install --cask rectangle",
    installMethod: "manual",
    cost: "free",
    tags: ["windows", "productivity"],
    url: "https://rectangleapp.com",
    related: ["alttab"],
    why: "No puedo vivir sin splits de terminal y editor en pantalla completa. Rectangle hace que Mac se comporte como deberia.",
  },
  {
    id: "betterdisplay",
    name: "BetterDisplay",
    category: "apps",
    subcategory: "utilidades",
    description: "Control avanzado de monitores. Resoluciones custom, brightness.",
    install: "brew install --cask betterdisplay",
    installMethod: "brew",
    cost: "freemium",
    tags: ["display", "monitor"],
    url: "https://betterdisplay.pro",
    related: [],
    why: "Para sacarle resoluciones custom al monitor externo sin que quede pixelado. Apple no da estas opciones de forma nativa.",
  },
  {
    id: "ice",
    name: "Ice",
    category: "apps",
    subcategory: "utilidades",
    description: "Menu bar manager. Oculta iconos para mantener la barra limpia.",
    install: "brew install --cask jordanbaird-ice",
    installMethod: "brew",
    cost: "free",
    tags: ["menubar", "productivity"],
    url: "https://icemenubar.app",
    related: ["stats"],
    why: "Con 20 apps abiertas la menu bar se convierte en un caos. Ice la mantiene limpia sin perder acceso a nada.",
  },
  {
    id: "stats",
    name: "Stats",
    category: "apps",
    subcategory: "utilidades",
    description: "Monitor del sistema en la menu bar. CPU, RAM, disco, red.",
    install: "brew install --cask stats",
    installMethod: "manual",
    cost: "free",
    tags: ["monitoring", "system"],
    url: "https://github.com/exelban/stats",
    related: ["htop", "ice"],
    why: "Un vistazo rapido a CPU y RAM sin abrir Activity Monitor. Cuando el fan arranca solo miro la barra y ya se que esta quemando.",
  },
  {
    id: "macs-fan-control",
    name: "Macs Fan Control",
    category: "apps",
    subcategory: "utilidades",
    description: "Control manual de ventiladores y monitoreo de temperatura.",
    install: "brew install --cask macs-fan-control",
    installMethod: "manual",
    cost: "freemium",
    tags: ["hardware", "temperature"],
    url: "https://crystalidea.com/macs-fan-control",
    related: ["stats"],
    why: "Cuando tengo modelos corriendo en local el Mac se convierte en una freidora. Esto me deja forzar el fan antes de que se queme.",
  },
  {
    id: "1password-cli",
    name: "1Password CLI",
    category: "apps",
    subcategory: "utilidades",
    description: "Acceso a passwords desde terminal. Secrets management.",
    install: "brew install --cask 1password-cli",
    installMethod: "brew",
    cost: "paid",
    tags: ["security", "passwords"],
    url: "https://1password.com",
    related: [],
    why: "Para inyectar secrets en scripts sin hardcodearlos. `op run` es una de las mejores integraciones de seguridad que existen para devs.",
  },
  {
    id: "cmux",
    name: "cmux",
    category: "apps",
    subcategory: "utilidades",
    description: "Multiplexor de sesiones Claude Code en paralelo.",
    install: "brew install --cask cmux",
    installMethod: "brew",
    cost: "free",
    tags: ["claude", "multiplexor"],
    url: "",
    related: ["claude-code-cli"],
    why: "Para correr multiples agentes de Claude Code en paralelo sin abrir 10 terminales. Multiplica la productividad cuando tenes tareas independientes.",
  },
  {
    id: "background-music",
    name: "Background Music",
    category: "apps",
    subcategory: "utilidades",
    description: "Control de audio por app. Volumen independiente, auto-pause.",
    install: "brew install --cask background-music",
    installMethod: "brew",
    cost: "free",
    tags: ["audio", "volume", "control"],
    url: "https://github.com/kyleneideck/BackgroundMusic",
    related: [],
    why: "Para bajar el volumen de Slack sin tocar Spotify. Control de audio por app que macOS deberia tener nativo.",
  },
  {
    id: "meetingbar",
    name: "MeetingBar",
    category: "apps",
    subcategory: "utilidades",
    description: "Proxima reunion en la menu bar. Un click para unirse.",
    install: "brew install --cask meetingbar",
    installMethod: "brew",
    cost: "free",
    tags: ["calendar", "meetings", "menubar"],
    url: "https://meetingbar.app",
    related: ["ice"],
    why: "Ver la proxima reunion en la barra y unirme con un click. No mas buscar el link en el calendario.",
  },
  {
    id: "raycast",
    name: "Raycast",
    category: "apps",
    subcategory: "utilidades",
    description: "Launcher y productivity app. Reemplaza Spotlight con extensions, snippets, window management.",
    install: "Download from raycast.com",
    installMethod: "manual",
    cost: "freemium",
    tags: ["launcher", "productivity", "automation"],
    url: "https://raycast.com",
    related: [],
    why: "Spotlight con esteroides. Extensions para todo: clipboard history, snippets, window management. Una vez que lo usas no hay vuelta atras.",
  },
  {
    id: "onyx",
    name: "OnyX",
    category: "apps",
    subcategory: "utilidades",
    description: "Utilidad de mantenimiento y optimizacion para macOS. Limpieza de cache, reparacion de permisos.",
    install: "Download from titanium-software.fr",
    installMethod: "manual",
    cost: "free",
    tags: ["maintenance", "optimization", "macos"],
    url: "https://titanium-software.fr/en/onyx.html",
    related: [],
    why: "Para limpiar caches, reparar permisos y hacer mantenimiento general de macOS. Lo corro cada par de meses cuando el Mac se siente lento.",
  },
  {
    id: "orca",
    name: "Orca",
    category: "apps",
    subcategory: "utilidades",
    description: "App de generacion de imagenes con AI. Stably AI.",
    install: "Download from stably.ai",
    installMethod: "manual",
    cost: "freemium",
    tags: ["ai", "images", "generation"],
    url: "https://stably.ai",
    related: [],
    why: "Para generar imagenes con AI local. Util para mockups rapidos y assets de prototipado sin depender de servicios web.",
  },
  {
    id: "rightfont",
    name: "RightFont",
    category: "apps",
    subcategory: "utilidades",
    description: "Gestor de fuentes para macOS. Preview, activacion, organizacion.",
    install: "Manual download",
    installMethod: "manual",
    cost: "freemium",
    tags: ["fonts", "design"],
    url: "https://rightfontapp.com",
    related: [],
    why: "Tengo cientos de fuentes instaladas y sin un gestor decente es un caos. RightFont me deja activarlas on-demand sin relentizar el sistema.",
  },
  // === Mac Apps: Browsers ===
  {
    id: "brave",
    name: "Brave Browser",
    category: "apps",
    subcategory: "browsers",
    description: "Browser con bloqueo de ads y trackers integrado.",
    install: "brew install --cask brave-browser",
    installMethod: "manual",
    cost: "free",
    tags: ["browser", "privacy"],
    url: "https://brave.com",
    related: ["chrome"],
    why: "Mi browser principal. Sin ads nativos y mucho mas rapido que Chrome en sitios pesados. La privacidad es un bonus.",
  },
  {
    id: "chrome",
    name: "Google Chrome",
    category: "apps",
    subcategory: "browsers",
    description: "Browser de Google. Sync, extensions, DevTools.",
    install: "brew install --cask google-chrome",
    installMethod: "brew",
    cost: "free",
    tags: ["browser", "google"],
    url: "https://www.google.com/chrome/",
    related: ["brave"],
    why: "Lo tengo por los DevTools y para testing cross-browser. Cuando el cliente usa Chrome necesito reproducir exactamente su entorno.",
  },
  // === Mac Apps: Comunicacion ===
  {
    id: "slack",
    name: "Slack",
    category: "apps",
    subcategory: "comunicacion",
    description: "Mensajeria para equipos. Canales, threads, integraciones.",
    install: "brew install --cask slack",
    installMethod: "manual",
    cost: "free",
    tags: ["communication", "team"],
    url: "https://slack.com",
    related: [],
    why: "El estandar de facto en equipos tech. No me gusta mucho pero todos estan ahi, asi que no hay opcion.",
  },
  {
    id: "beeper",
    name: "Beeper",
    category: "apps",
    subcategory: "comunicacion",
    description: "Mensajeria unificada. iMessage, WhatsApp, Telegram, Discord en una app.",
    install: "Download from beeper.com",
    installMethod: "manual",
    cost: "free",
    tags: ["messaging", "unified"],
    url: "https://beeper.com",
    related: ["slack"],
    why: "Tener iMessage, WhatsApp y Telegram en una sola ventana es un game changer para el foco. Menos cambios de contexto = mas productividad.",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "apps",
    subcategory: "comunicacion",
    description: "Streaming de musica y podcasts.",
    install: "brew install --cask spotify",
    installMethod: "manual",
    cost: "freemium",
    tags: ["music", "streaming"],
    url: "https://spotify.com",
    related: [],
    why: "No codifico sin musica. Playlists de lo-fi y electronic para entrar en flow. El algoritmo de discovery es bastante bueno.",
  },
  // === Mac Apps: Seguridad ===
  {
    id: "cloudflare-warp",
    name: "Cloudflare WARP",
    category: "apps",
    subcategory: "seguridad",
    description: "VPN y DNS seguro. Encripta trafico de red.",
    install: "brew install --cask cloudflare-warp",
    installMethod: "manual",
    cost: "free",
    tags: ["vpn", "security", "dns"],
    url: "https://1.1.1.1",
    related: [],
    why: "DNS rapido y encriptado sin la complejidad de una VPN corporativa. Lo activo en redes publicas sin pensarlo dos veces.",
  },
  {
    id: "drata",
    name: "Drata Agent",
    category: "apps",
    subcategory: "seguridad",
    description: "Agente de compliance (SOC2, ISO). Monitorea configuracion de seguridad.",
    install: "Enterprise install",
    installMethod: "manual",
    cost: "paid",
    tags: ["compliance", "security"],
    url: "https://drata.com",
    related: [],
    why: "Requerimiento de la empresa para SOC2. No lo instale por gusto pero hace el compliance automatico en segundo plano sin molestar.",
  },
  // === CLI: AI Coding Agents ===
  {
    id: "claude-code-cli",
    name: "Claude Code",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Claude Code. Coding agent en terminal.",
    install: "pnpm install -g @anthropic-ai/claude-code",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding", "claude"],
    url: "https://docs.anthropic.com/en/docs/claude-code",
    related: ["gemini-cli", "codex-cli"],
    why: "El mejor coding agent que existe hoy. Lo uso para casi todo: refactors, debugging, PRs. Ha reemplazado el 70% de mi tiempo de coding manual.",
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI oficial de Google Gemini. Coding agent en terminal.",
    install: "pnpm install -g @google/gemini-cli",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding", "google"],
    url: "https://github.com/google-gemini/gemini-cli",
    related: ["claude-code-cli", "codex-cli"],
    why: "Lo tengo para benchmarks y para tareas donde el contexto largo de Gemini importa. Util para comparar resultados con Claude Code.",
  },
  {
    id: "codex-cli",
    name: "OpenAI Codex",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de OpenAI. Coding agent en terminal.",
    install: "pnpm install -g @openai/codex",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding", "openai"],
    url: "https://github.com/openai/codex",
    related: ["claude-code-cli", "gemini-cli"],
    why: "Alternativa a Claude Code para proyectos donde el cliente es fan de OpenAI. Lo mantengo instalado para no tener sorpresas.",
  },
  {
    id: "kilo-code",
    name: "Kilo Code",
    category: "cli",
    subcategory: "ai-agents",
    description: "CLI de Kilo Code. Coding agent en terminal.",
    install: "pnpm install -g @kilocode/cli",
    installMethod: "pnpm",
    cost: "free",
    tags: ["ai", "coding"],
    url: "",
    related: ["claude-code-cli"],
    why: "Lo estoy explorando como alternativa open-source a los agents principales. Prometedor para workflows que necesitan mas control.",
  },
  // === CLI: Browser & Automation ===
  {
    id: "agent-browser",
    name: "agent-browser",
    category: "cli",
    subcategory: "browser-automation",
    description: "Browser automation CLI para AI agents.",
    install: "pnpm install -g agent-browser",
    installMethod: "pnpm",
    cost: "free",
    tags: ["browser", "automation"],
    url: "",
    related: [],
    why: "Para automatizar flujos web desde agentes AI sin levantar Playwright manual. Se integra directo con Claude Code.",
  },
  // === CLI: Dev Tools ===
  {
    id: "op-cli",
    name: "OP",
    category: "cli",
    subcategory: "dev-tools",
    description: "CLI de OP. Herramienta de desarrollo.",
    install: "pnpm install -g op",
    installMethod: "pnpm",
    cost: "free",
    tags: ["dev"],
    url: "",
    related: [],
    why: "Herramienta de dev para operaciones especificas del stack. Lo uso en scripts de automatizacion internos.",
  },
  {
    id: "asciinema",
    name: "asciinema",
    category: "cli",
    subcategory: "dev-tools",
    description: "Grabador de sesiones de terminal. Genera recordings reproducibles y compartibles.",
    install: "brew install asciinema",
    installMethod: "brew",
    cost: "free",
    tags: ["terminal", "recording", "demo"],
    url: "https://asciinema.org",
    related: ["tmux"],
    why: "Para grabar demos de herramientas CLI. Mucho mejor que un GIF — se puede copiar texto del recording y pesa nada.",
  },
  {
    id: "imagemagick",
    name: "ImageMagick",
    category: "cli",
    subcategory: "dev-tools",
    description: "Suite de procesamiento de imagenes desde CLI. Conversion, resize, composicion.",
    install: "brew install imagemagick",
    installMethod: "brew",
    cost: "free",
    tags: ["images", "processing", "conversion"],
    url: "https://imagemagick.org",
    related: ["ffmpeg"],
    why: "El ffmpeg de las imagenes. Batch resize, conversion entre formatos, watermarks — todo desde un script.",
  },
  // === CLI: Package Managers & Deploy ===
  {
    id: "pnpm",
    name: "pnpm",
    category: "cli",
    subcategory: "package-managers",
    description: "Package manager rapido y eficiente en disco.",
    install: "npm install -g pnpm",
    installMethod: "npm",
    cost: "free",
    tags: ["package-manager", "node"],
    url: "https://pnpm.io",
    related: ["uv"],
    why: "npm es lento y devora disco con node_modules duplicados. pnpm usa symlinks y es 2-3x mas rapido en installs. No vuelvo atras.",
  },
  {
    id: "uv",
    name: "uv",
    category: "cli",
    subcategory: "package-managers",
    description: "Python package manager ultra rapido. Escrito en Rust.",
    install: "curl -LsSf https://astral.sh/uv/install.sh | sh",
    installMethod: "curl",
    cost: "free",
    tags: ["package-manager", "python", "rust"],
    url: "https://docs.astral.sh/uv/",
    related: ["pnpm"],
    why: "pip es del siglo pasado. uv instala dependencias de Python en segundos, no minutos. Escrito en Rust, se nota.",
  },
  {
    id: "vercel-cli",
    name: "Vercel",
    category: "cli",
    subcategory: "package-managers",
    description: "CLI para deploy de apps web.",
    install: "pnpm install -g vercel",
    installMethod: "pnpm",
    cost: "freemium",
    tags: ["deploy", "hosting"],
    url: "https://vercel.com",
    related: [],
    why: "Deploy de frontend en segundos con `vercel`. Perfecto para probar cambios en produccion sin pipeline completo.",
  },
  // === CLI: Terminal Tools ===
  {
    id: "tmux",
    name: "tmux",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Multiplexor de terminal. Sesiones persistentes, splits.",
    install: "brew install tmux",
    installMethod: "brew",
    cost: "free",
    tags: ["terminal", "multiplexor"],
    url: "https://github.com/tmux/tmux",
    related: [],
    why: "No abro terminal sin tmux. Splits + sesiones persistentes = productividad. Si se cae la SSH, la sesion sigue viva.",
  },
  {
    id: "fzf",
    name: "fzf",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Fuzzy finder. Ctrl+R mejorado, busqueda de archivos.",
    install: "brew install fzf",
    installMethod: "brew",
    cost: "free",
    tags: ["search", "fuzzy", "terminal"],
    url: "https://github.com/junegunn/fzf",
    related: [],
    why: "Ctrl+R sin fzf es como buscar en Google sin autocompletado. Tambien lo uso para seleccionar branches y archivos en pipelines.",
  },
  {
    id: "htop",
    name: "htop",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Monitor de procesos interactivo. Mejor que top.",
    install: "brew install htop",
    installMethod: "brew",
    cost: "free",
    tags: ["monitoring", "processes"],
    url: "https://htop.dev",
    related: ["stats", "aitop"],
    why: "Para ver que proceso esta comiendo CPU sin salir de la terminal. Mucho mas legible que top.",
  },
  {
    id: "aitop",
    name: "aitop",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Monitor del sistema con AI. Top-like con analisis inteligente.",
    install: "brew install aitop",
    installMethod: "brew",
    cost: "free",
    tags: ["monitoring", "ai"],
    url: "",
    related: ["htop"],
    why: "Lo probé porque la combinacion de AI + monitoreo me parecio curiosa. Util cuando queres que te explique por que algo esta lento.",
  },
  {
    id: "ffmpeg",
    name: "ffmpeg",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Procesamiento de audio/video. Conversion, encoding.",
    install: "brew install ffmpeg",
    installMethod: "brew",
    cost: "free",
    tags: ["media", "video", "audio"],
    url: "https://ffmpeg.org",
    related: [],
    why: "Para convertir videos de demos, recortar screencasts y comprimir grabaciones antes de compartir. Un one-liner reemplaza cualquier app GUI.",
  },
  {
    id: "ncdu",
    name: "ncdu",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Analizador de uso de disco con interfaz ncurses.",
    install: "brew install ncdu",
    installMethod: "brew",
    cost: "free",
    tags: ["disk", "storage"],
    url: "https://dev.yorhel.nl/ncdu",
    related: [],
    why: "Cuando el disco esta lleno y no se que ocupa el espacio. ncdu me muestra exactamente donde esta el problema en segundos.",
  },
  {
    id: "gh",
    name: "gh",
    category: "cli",
    subcategory: "terminal-tools",
    description: "CLI oficial de GitHub. PRs, issues, repos desde terminal.",
    install: "brew install gh",
    installMethod: "brew",
    cost: "free",
    tags: ["github", "git"],
    url: "https://cli.github.com",
    related: [],
    why: "Para crear PRs y revisar issues sin salir de la terminal. Lo uso constantemente con Claude Code para el ciclo completo de PR.",
  },
  {
    id: "jq",
    name: "jq",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Procesador de JSON en linea de comandos.",
    install: "brew install jq",
    installMethod: "brew",
    cost: "free",
    tags: ["json", "parsing"],
    url: "https://jqlang.github.io/jq/",
    related: [],
    why: "Parsear respuestas de APIs en scripts sin escribir Python. `curl ... | jq '.data[]'` es magia pura.",
  },
  {
    id: "shellcheck",
    name: "shellcheck",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Linter para scripts shell. Encuentra bugs y problemas.",
    install: "brew install shellcheck",
    installMethod: "brew",
    cost: "free",
    tags: ["linter", "shell"],
    url: "https://www.shellcheck.net",
    related: [],
    why: "Los scripts bash son faciles de arruinar. shellcheck atrapa los errores clasicos antes de que los encuentres a las 3am en produccion.",
  },
  {
    id: "nvtop",
    name: "nvtop",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Monitor de GPU (similar a htop para GPUs).",
    install: "brew install nvtop",
    installMethod: "brew",
    cost: "free",
    tags: ["gpu", "monitoring"],
    url: "https://github.com/Syllo/nvtop",
    related: ["htop"],
    why: "Para monitorear VRAM y carga de GPU cuando entreno modelos localmente. El equivalente de htop pero para GPUs.",
  },
  {
    id: "deno",
    name: "Deno",
    category: "cli",
    subcategory: "dev-tools",
    description: "Runtime de JS/TS con seguridad por defecto. Alternativa moderna a Node.",
    install: "brew install deno",
    installMethod: "brew",
    cost: "free",
    tags: ["runtime", "javascript", "typescript"],
    url: "https://deno.com",
    related: ["pnpm"],
    why: "Lo uso para scripts rapidos de TS sin config. Viene con formatter, linter y test runner built-in.",
  },
  {
    id: "go",
    name: "Go",
    category: "cli",
    subcategory: "dev-tools",
    description: "Lenguaje compilado de Google. Concurrente, tipado, rapido.",
    install: "brew install go",
    installMethod: "brew",
    cost: "free",
    tags: ["language", "compiled", "concurrency"],
    url: "https://go.dev",
    related: ["deno"],
    why: "Necesario para compilar herramientas como mole y rtk. Tambien lo uso para CLIs rapidos.",
  },
  {
    id: "rtk",
    name: "RTK (Rust Token Killer)",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Proxy CLI que ahorra 60-90% de tokens en operaciones de dev.",
    install: "brew install rtk",
    installMethod: "brew",
    cost: "free",
    tags: ["cli", "tokens", "proxy", "optimization"],
    url: "https://github.com/nicholasgasior/rtk",
    related: ["claude-code-cli"],
    why: "Reduce drasticamente el consumo de tokens en Claude Code. Se interpone como proxy en git, ls, etc. Imprescindible.",
  },
  {
    id: "bats-core",
    name: "bats-core",
    category: "cli",
    subcategory: "dev-tools",
    description: "Framework de testing para scripts Bash.",
    install: "brew install bats-core",
    installMethod: "brew",
    cost: "free",
    tags: ["testing", "bash", "shell"],
    url: "https://github.com/bats-core/bats-core",
    related: ["shellcheck"],
    why: "Para testear scripts de shell de forma automatizada. Lo uso con shellcheck para CI de scripts.",
  },
  {
    id: "sox",
    name: "sox",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Procesamiento de audio en linea de comandos. Grabacion, conversion, efectos.",
    install: "brew install sox",
    installMethod: "brew",
    cost: "free",
    tags: ["audio", "processing", "cli"],
    url: "https://sox.sourceforge.net",
    related: ["ffmpeg"],
    why: "El ffmpeg del audio. Lo uso para procesar grabaciones y convertir formatos desde la terminal.",
  },
  {
    id: "tectonic",
    name: "tectonic",
    category: "cli",
    subcategory: "dev-tools",
    description: "Compilador de LaTeX moderno. Descarga paquetes automaticamente.",
    install: "brew install tectonic",
    installMethod: "brew",
    cost: "free",
    tags: ["latex", "documents", "pdf"],
    url: "https://tectonic-typesetting.github.io",
    related: [],
    why: "Compila LaTeX sin necesitar una instalacion completa de TeX. Perfecto para papers y documentos academicos.",
  },
  {
    id: "mole",
    name: "mole",
    category: "cli",
    subcategory: "terminal-tools",
    description: "SSH tunneling simplificado. Crea tunnels con un comando.",
    install: "brew install mole",
    installMethod: "brew",
    cost: "free",
    tags: ["ssh", "tunneling", "networking"],
    url: "https://github.com/davrodpin/mole",
    related: [],
    why: "Hace SSH tunneling trivial. Un comando y tienes acceso a la DB de staging desde localhost.",
  },
  {
    id: "postgresql",
    name: "PostgreSQL 15",
    category: "cli",
    subcategory: "dev-tools",
    description: "Base de datos relacional. El estandar de la industria.",
    install: "brew install postgresql@15",
    installMethod: "brew",
    cost: "free",
    tags: ["database", "sql", "relational"],
    url: "https://www.postgresql.org",
    related: ["redis"],
    why: "Mi base de datos por defecto para cualquier proyecto serio. Con pgvector para embeddings es imbatible.",
  },
  {
    id: "redis",
    name: "Redis",
    category: "cli",
    subcategory: "dev-tools",
    description: "Base de datos in-memory. Cache, queues, pub/sub.",
    install: "brew install redis",
    installMethod: "brew",
    cost: "free",
    tags: ["database", "cache", "in-memory"],
    url: "https://redis.io",
    related: ["postgresql"],
    why: "Cache y queues. Lo uso para rate limiting, sesiones, y como broker de mensajes entre servicios.",
  },
  {
    id: "glow",
    name: "Glow",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Render de Markdown en la terminal con syntax highlighting y paginacion.",
    install: "brew install glow",
    installMethod: "brew",
    cost: "free",
    tags: ["markdown", "terminal", "reader"],
    url: "https://github.com/charmbracelet/glow",
    related: ["jq"],
    why: "Para leer READMEs y docs sin salir de la terminal. Render bonito de Markdown directo en zsh.",
  },
  {
    id: "mas",
    name: "mas",
    category: "cli",
    subcategory: "terminal-tools",
    description: "CLI para Mac App Store. Instalar, actualizar y buscar apps desde la terminal.",
    install: "brew install mas",
    installMethod: "brew",
    cost: "free",
    tags: ["macos", "app-store", "cli"],
    url: "https://github.com/mas-cli/mas",
    related: [],
    why: "Automatiza instalaciones del App Store. Lo uso en setup.sh para las apps que solo estan ahi.",
  },
  {
    id: "git-filter-repo",
    name: "git-filter-repo",
    category: "cli",
    subcategory: "dev-tools",
    description: "Reescribir historial de git de forma segura. Reemplaza filter-branch.",
    install: "brew install git-filter-repo",
    installMethod: "brew",
    cost: "free",
    tags: ["git", "history", "cleanup"],
    url: "https://github.com/newren/git-filter-repo",
    related: ["gh"],
    why: "Para limpiar historiales de git cuando se filtra algo sensible o se necesita extraer un subdirectorio. Mucho mas seguro que filter-branch.",
  },
  {
    id: "zig",
    name: "Zig",
    category: "cli",
    subcategory: "dev-tools",
    description: "Lenguaje de programacion de sistemas. Compilador y build system.",
    install: "brew install zig",
    installMethod: "brew",
    cost: "free",
    tags: ["systems", "programming", "compiler"],
    url: "https://ziglang.org",
    related: ["go"],
    why: "Para programacion de sistemas de bajo nivel. Build system excelente y buen complemento a Rust/Go.",
  },
  {
    id: "ruff",
    name: "Ruff",
    category: "cli",
    subcategory: "dev-tools",
    description: "Linter y formatter para Python. Ultra rapido, reemplaza flake8+isort+black.",
    install: "uv tool install ruff",
    installMethod: "uv",
    cost: "free",
    tags: ["python", "linter", "formatter"],
    url: "https://docs.astral.sh/ruff",
    related: ["uv", "pre-commit"],
    why: "Reemplaza 5 herramientas Python en una sola. Rapido porque esta en Rust. Lo uso en todos mis proyectos.",
  },
  {
    id: "pre-commit",
    name: "pre-commit",
    category: "cli",
    subcategory: "dev-tools",
    description: "Framework de hooks para git. Ejecuta linters y checks antes de cada commit.",
    install: "uv tool install pre-commit",
    installMethod: "uv",
    cost: "free",
    tags: ["git", "hooks", "linting", "ci"],
    url: "https://pre-commit.com",
    related: ["ruff", "shellcheck", "prek"],
    why: "Asegura que nunca hago commit de codigo roto. Corre ruff, shellcheck y mas automaticamente.",
  },
  {
    id: "prek",
    name: "prek",
    category: "cli",
    subcategory: "dev-tools",
    description: "Wrapper de pre-commit mas rapido. Escrito en Go, cachea resultados.",
    install: "brew install j178/tap/prek",
    installMethod: "brew",
    cost: "free",
    tags: ["git", "hooks", "linting"],
    url: "https://github.com/j178/prek",
    related: ["pre-commit"],
    why: "Pre-commit pero rapido. Cachea resultados y solo corre hooks en archivos modificados. Lo uso en vez de pre-commit directo.",
  },
  {
    id: "complexipy",
    name: "complexipy",
    category: "cli",
    subcategory: "dev-tools",
    description: "Analizador de complejidad cognitiva para Python. Detecta funciones dificiles de mantener.",
    install: "uv tool install complexipy",
    installMethod: "uv",
    cost: "free",
    tags: ["python", "complexity", "code-quality"],
    url: "https://github.com/rohaquinern/complexipy",
    related: ["ruff"],
    why: "Mi proyecto. Mide complejidad cognitiva de codigo Python para saber que refactorizar primero.",
  },
  {
    id: "code-review-graph",
    name: "code-review-graph",
    category: "cli",
    subcategory: "dev-tools",
    description: "MCP server para busqueda semantica de codigo. Grafo de dependencias y analisis de impacto.",
    install: "uv tool install code-review-graph",
    installMethod: "uv",
    cost: "free",
    tags: ["mcp", "code-review", "semantic-search", "graph"],
    url: "https://github.com/sebastianbreguel/code-review-graph",
    related: ["rtk", "claude-code-cli"],
    why: "Mi proyecto. Busca codigo por semantica en vez de grep. get_impact_radius > 10 greps. Ahorra ~70% tokens.",
  },
  {
    id: "yt-dlp",
    name: "yt-dlp",
    category: "cli",
    subcategory: "terminal-tools",
    description: "Descargador de video/audio de YouTube y +1000 sitios. Fork mejorado de youtube-dl.",
    install: "uv tool install yt-dlp",
    installMethod: "uv",
    cost: "free",
    tags: ["video", "download", "youtube"],
    url: "https://github.com/yt-dlp/yt-dlp",
    related: ["ffmpeg"],
    why: "Para descargar videos y audio de YouTube. Con ffmpeg convierte a cualquier formato.",
  },
  {
    id: "nvm",
    name: "NVM",
    category: "cli",
    subcategory: "package-managers",
    description: "Node Version Manager. Instalar y cambiar entre versiones de Node.js.",
    install: "brew install nvm",
    installMethod: "brew",
    cost: "free",
    tags: ["node", "version-manager", "javascript"],
    url: "https://github.com/nvm-sh/nvm",
    related: ["pnpm"],
    why: "Indispensable para manejar multiples versiones de Node. Cada proyecto puede tener su version sin conflictos.",
  },
  // === Shell Setup ===
  {
    id: "oh-my-zsh",
    name: "Oh My Zsh",
    category: "shell",
    subcategory: "shell",
    description: "Framework para Zsh. Aliases, plugins, themes. La base de todo.",
    install: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
    installMethod: "curl",
    cost: "free",
    tags: ["shell", "zsh", "framework"],
    url: "https://ohmyz.sh",
    related: ["powerlevel10k", "zsh-autosuggestions"],
    why: "La base de mi shell setup. Sin Oh My Zsh mi terminal se siente desnuda. Los aliases y plugins vienen solos.",
  },
  {
    id: "powerlevel10k",
    name: "Powerlevel10k",
    category: "shell",
    subcategory: "shell",
    description: "Theme ultra rapido con prompt customizable y iconos.",
    install: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k",
    installMethod: "git",
    cost: "free",
    tags: ["shell", "theme", "prompt"],
    url: "https://github.com/romkatv/powerlevel10k",
    related: ["oh-my-zsh"],
    why: "El prompt mas rapido y customizable que existe. Ver el git branch, estado de uv y tiempo de ejecucion en el prompt cambia la vida.",
  },
  {
    id: "zsh-autosuggestions",
    name: "zsh-autosuggestions",
    category: "shell",
    subcategory: "shell",
    description: "Sugiere comandos del historial mientras escribes.",
    install: "brew install zsh-autosuggestions",
    installMethod: "brew",
    cost: "free",
    tags: ["shell", "zsh", "productivity"],
    url: "https://github.com/zsh-users/zsh-autosuggestions",
    related: ["oh-my-zsh", "fzf"],
    why: "Autocompletado de comandos del historial en tiempo real. Escribo las primeras letras y presiono la flecha. No vuelvo a una shell sin esto.",
  },
  {
    id: "fzf-shell",
    name: "fzf (shell integration)",
    category: "shell",
    subcategory: "shell",
    description: "Fuzzy finder integrado en la shell. Ctrl+R mejorado.",
    install: "brew install fzf",
    installMethod: "brew",
    cost: "free",
    tags: ["shell", "search", "fuzzy"],
    url: "https://github.com/junegunn/fzf",
    related: ["oh-my-zsh"],
    why: "Con la integracion en shell, Ctrl+R se convierte en un buscador fuzzy del historial. Nunca mas escribo comandos largos de memoria.",
  },
  // === Claude Code: Plugins ===
  {
    id: "plugin-context-mode",
    name: "context-mode",
    category: "claude-code",
    subcategory: "plugins",
    description: "Optimiza el context window ejecutando comandos en sandbox. Ahorra ~80% de tokens.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "optimization", "tokens"],
    url: "",
    related: ["plugin-superpowers"],
    why: "Lo construi para no quemar contexto en outputs largos. Ahorra ~80% de tokens reales en sesiones de trabajo intenso.",
  },
  {
    id: "plugin-code-simplifier",
    name: "code-simplifier",
    category: "claude-code",
    subcategory: "plugins",
    description: "Revisa codigo modificado para simplificar, mejorar calidad y encontrar issues.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "code-quality"],
    url: "",
    related: ["agent-code-simplifier"],
    why: "Lo configure para que Claude revise automaticamente el codigo que genera. Es como tener un code reviewer siempre activo.",
  },
  {
    id: "plugin-context7",
    name: "context7",
    category: "claude-code",
    subcategory: "plugins",
    description: "Context7 MCP server para busqueda de documentacion en tiempo real.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "docs", "search"],
    url: "",
    related: [],
    why: "Claude deja de alucinar APIs cuando tiene docs reales. Context7 inyecta documentacion actualizada al contexto automaticamente.",
  },
  {
    id: "plugin-frontend-design",
    name: "frontend-design",
    category: "claude-code",
    subcategory: "plugins",
    description: "Herramientas de disenio frontend: componentes, layouts, CSS.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "frontend", "design"],
    url: "",
    related: [],
    why: "Para construir componentes UI rapidamente con Claude. Le da contexto de disenio que mejora mucho la calidad del output visual.",
  },
  {
    id: "plugin-playwright",
    name: "playwright",
    category: "claude-code",
    subcategory: "plugins",
    description: "Browser automation via Playwright MCP. Testing, scraping, interaccion web.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "browser", "testing"],
    url: "",
    related: ["agent-browser"],
    why: "Le da ojos a Claude Code. Puede navegar, clickear y hacer screenshots sin que yo escriba una linea de Playwright.",
  },
  {
    id: "plugin-skill-creator",
    name: "skill-creator",
    category: "claude-code",
    subcategory: "plugins",
    description: "Crea, modifica y mide rendimiento de skills custom para Claude Code.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "skills"],
    url: "",
    related: [],
    why: "Lo uso para iterar en mis propios skills. Me permite medir si un skill nuevo realmente mejora los resultados antes de committear.",
  },
  {
    id: "plugin-superpowers",
    name: "superpowers",
    category: "claude-code",
    subcategory: "plugins",
    description: "Superpowers: writing-plans, executing-plans, brainstorming, systematic-debugging.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "workflow", "planning"],
    url: "",
    related: ["plugin-context-mode"],
    why: "El plugin mas importante del toolkit. Estructura el workflow de Claude en fases: plan, ejecutar, verificar. Sin el, Claude improvisa demasiado.",
  },
  {
    id: "plugin-claude-hud",
    name: "claude-hud",
    category: "claude-code",
    subcategory: "plugins",
    description: "HUD (Heads-Up Display) para Claude Code. Status line con info en tiempo real.",
    install: "Claude Code marketplace",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "ui", "monitoring"],
    url: "",
    related: [],
    why: "Ver tokens usados, costo de la sesion y status de herramientas en tiempo real. Antes lo corre a ciegas, ahora tengo datos.",
  },
  {
    id: "plugin-caveman",
    name: "caveman",
    category: "claude-code",
    subcategory: "plugins",
    description: "Modo cavernicola. Comprime respuestas 50-75% eliminando relleno, articulos y filler.",
    install: "Claude Code marketplace (github:JuliusBrussee/caveman)",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "tokens", "compression"],
    url: "https://github.com/JuliusBrussee/caveman",
    related: ["rtk", "plugin-context-mode"],
    why: "Ahorra 50-75% de tokens en respuestas. Sin filler, sin articulos, solo sustancia. Parte clave del stack de optimizacion.",
  },
  {
    id: "plugin-code-review",
    name: "code-review",
    category: "claude-code",
    subcategory: "plugins",
    description: "Plugin oficial de Anthropic para code review de PRs.",
    install: "Claude Code marketplace (anthropics/claude-code)",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "code-review", "pr"],
    url: "https://github.com/anthropics/claude-code",
    related: ["plugin-superpowers"],
    why: "Review automatizado de PRs con checklist de bugs, seguridad y convenciones del proyecto.",
  },
  {
    id: "plugin-compound-engineering",
    name: "compound-engineering",
    category: "claude-code",
    subcategory: "plugins",
    description: "Mega-plugin de Compound Engineering. Code review multi-agente, commits, PRs, debugging, planificacion, worktrees.",
    install: "Claude Code marketplace (EveryInc/compound-engineering-plugin)",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "workflow", "review", "planning"],
    url: "https://github.com/EveryInc/compound-engineering-plugin",
    related: ["plugin-superpowers", "plugin-code-review"],
    why: "El plugin mas completo. Code review con agentes especializados, commits inteligentes, PRs con descripcion automatica. Reemplazo varios workflows manuales de un saque.",
  },
  {
    id: "plugin-codex",
    name: "codex",
    category: "claude-code",
    subcategory: "plugins",
    description: "Integracion con OpenAI Codex CLI. Permite delegar tareas a Codex desde Claude Code.",
    install: "Claude Code marketplace (openai/codex-plugin-cc)",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "openai", "codex"],
    url: "https://github.com/openai/codex-plugin-cc",
    related: ["codex-cli"],
    why: "Para tener Codex como fallback cuando necesito otra perspectiva o el modelo de OpenAI es mejor para una tarea especifica.",
  },
  {
    id: "plugin-claude-code-setup",
    name: "claude-code-setup",
    category: "claude-code",
    subcategory: "plugins",
    description: "Asistente de setup inicial de Claude Code. Genera CLAUDE.md, sugiere hooks y automatizaciones.",
    install: "Claude Code marketplace (anthropics/claude-code)",
    installMethod: "marketplace",
    cost: "free",
    tags: ["claude", "setup", "onboarding"],
    url: "https://github.com/anthropics/claude-code",
    related: ["plugin-superpowers"],
    why: "Para onboarding de nuevos repos. Genera configuracion inicial basada en el proyecto detectado.",
  },
  // === Claude Code: Skills ===
  {
    id: "skill-browser-automation",
    name: "/browser-automation",
    category: "claude-code",
    subcategory: "skills",
    description: "Browser automation CLI. Navegacion, forms, scraping, screenshots.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "browser", "automation"],
    url: "",
    related: ["agent-browser"],
    why: "Para automatizar cualquier tarea web sin escribir Playwright manual. Lo construi para scraping y testing de flujos de usuario.",
  },
  {
    id: "skill-dream",
    name: "/dream",
    category: "claude-code",
    subcategory: "skills",
    description: "Consolidacion de memoria multi-fase. Merge updates, pruning.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "memory"],
    url: "",
    related: [],
    why: "Para consolidar y podar la memoria de Claude entre sesiones largas. Como un GC para el contexto acumulado.",
  },
  {
    id: "skill-health",
    name: "/health",
    category: "claude-code",
    subcategory: "skills",
    description: "Diagnostico cuando Claude se siente lento o ignora reglas. Audita hooks y MCP.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "diagnostics"],
    url: "",
    related: [],
    why: "Lo construi para cuando Claude empieza a portarse raro. Diagnostica hooks, MCPs y configuracion en un solo comando.",
  },
  {
    id: "skill-panel",
    name: "/panel",
    category: "claude-code",
    subcategory: "skills",
    description: "Panel de 3 lentes: simplificacion, arquitectura, producto. Multi-perspectiva.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "review", "decision"],
    url: "",
    related: [],
    why: "Para evaluar decisiones desde 3 angulos antes de comprometerse. Simplifica, revisa estructura, y valida producto en una sola pasada.",
  },
  {
    id: "skill-humanizer",
    name: "/humanizer",
    category: "claude-code",
    subcategory: "skills",
    description: "Elimina patrones de escritura AI del texto. Basado en la guia de Wikipedia.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "writing", "quality"],
    url: "",
    related: [],
    why: "Para que el texto no suene a robot. Detecta y corrige el lenguaje inflado tipico de AI antes de publicar cualquier cosa.",
  },
  {
    id: "skill-usage",
    name: "/usage",
    category: "claude-code",
    subcategory: "skills",
    description: "Muestra conteos de invocaciones de agentes, skills y plugins.",
    install: "Built-in skill",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "analytics", "usage"],
    url: "",
    related: [],
    why: "Para saber que herramientas uso mas y cuales estan juntando polvo. Datos reales sobre mi workflow con Claude.",
  },
  // === Claude Code: Agents ===
  {
    id: "agent-tech-lead",
    name: "tech-lead",
    category: "claude-code",
    subcategory: "agents",
    description: "Decisiones tecnicas, coordinacion cross-domain.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "architecture"],
    url: "",
    related: [],
    why: "El coordinador principal para decisiones que cruzan multiples dominios. Lo despachamos cuando la decision es demasiado grande para un solo agente.",
  },
  {
    id: "agent-code-simplifier",
    name: "code-simplifier",
    category: "claude-code",
    subcategory: "agents",
    description: "Simplificar, refactorizar y limpiar codigo.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "refactoring"],
    url: "",
    related: [],
    why: "Para eliminar complejidad innecesaria. Le paso codigo verboso y lo devuelve limpio sin perder funcionalidad.",
  },
  {
    id: "agent-ai-ml-expert",
    name: "ai-ml-expert",
    category: "claude-code",
    subcategory: "agents",
    description: "Prompts, RAG, embeddings, model selection.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "ai", "ml"],
    url: "",
    related: ["agent-prompt-engineering"],
    why: "Para decisiones de arquitectura AI/ML: que modelo usar, como estructurar un RAG, que estrategia de embeddings. Mi experto interno.",
  },
  {
    id: "agent-prompt-engineering",
    name: "prompt-engineering",
    category: "claude-code",
    subcategory: "agents",
    description: "Craft y optimizar prompts para LLMs.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "prompts"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "Para iterar en prompts de manera sistematica. Analiza por que un prompt falla y sugiere variantes con razonamiento.",
  },
  {
    id: "agent-data-science",
    name: "data-science-analytics",
    category: "claude-code",
    subcategory: "agents",
    description: "EDA, estadisticas, visualizacion, ML.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "data"],
    url: "",
    related: [],
    why: "Para analisis exploratorios rapidos. Le paso un dataset y me da EDA completo con estadisticas y visualizaciones listas.",
  },
  {
    id: "agent-data-pipeline",
    name: "data-pipeline-engineer",
    category: "claude-code",
    subcategory: "agents",
    description: "ETL/ELT, orchestration, ML workflows, FastAPI + data stores.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "data", "pipeline"],
    url: "",
    related: ["agent-data-science"],
    why: "Para disenar y debuggear pipelines de datos. Entiende Prefect, FastAPI, y todo lo que conecta la ingesta con el modelo.",
  },
  {
    id: "agent-ceo-strategist",
    name: "ceo-product-strategist",
    category: "claude-code",
    subcategory: "agents",
    description: "Vision estrategica CEO, roadmap, impacto de producto.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "strategy"],
    url: "",
    related: [],
    why: "Para pensar en impacto de producto mas alla del codigo. Util para preparar pitches y decidir que features priorizar con logica de negocio.",
  },
  {
    id: "agent-andrej-karpathy",
    name: "andrej-karpathy",
    category: "claude-code",
    subcategory: "agents",
    description: "Persona de Karpathy: implementaciones simples, first-principles, code review minimalista.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "ai", "persona"],
    url: "",
    related: ["agent-ai-ml-expert"],
    why: "Para cuando necesito una opinion brutal sobre complejidad innecesaria. Karpathy siempre elige lo mas simple que funcione.",
  },
  {
    id: "agent-ops-impact",
    name: "ops-impact-analyst",
    category: "claude-code",
    subcategory: "agents",
    description: "ROI de features, metricas de negocio, reportes ejecutivos.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "business"],
    url: "",
    related: ["agent-ceo-strategist"],
    why: "Para conectar metricas tecnicas con impacto de negocio. Convierte 'mejoramos latencia 200ms' en 'ahorramos $X/mes'.",
  },
  {
    id: "agent-tw93",
    name: "tw93",
    category: "claude-code",
    subcategory: "agents",
    description: "Gatekeeper de Mole: minimalismo, safety-first, scope discipline.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "review"],
    url: "",
    related: [],
    why: "Simula al maintainer upstream de Mole para evaluar si un PR seria aceptado. Filtra scope creep antes de escribir codigo.",
  },
  {
    id: "agent-database-engineer",
    name: "database-engineer",
    category: "claude-code",
    subcategory: "agents",
    description: "Disenio de esquemas, optimizacion de queries, modelado relacional.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "database"],
    url: "",
    related: ["postgresql"],
    why: "Para decisiones de disenio de base de datos: normalizacion, indices, relaciones. Mi experto en SQL y modelado.",
  },
  {
    id: "agent-coo",
    name: "coo",
    category: "claude-code",
    subcategory: "agents",
    description: "Perspectiva de scale-stage operator y customer-first product critique.",
    install: "Auto-dispatched by Claude Code",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "agent", "product", "customer"],
    url: "",
    related: ["agent-ceo-strategist", "agent-ops-impact"],
    why: "Evalua features desde la perspectiva del comprador: CCO, super-admin, owner. Si el cliente no lo pediria, no se construye.",
  },
  {
    id: "skill-sync-dotfiles",
    name: "Sync Dotfiles",
    category: "claude-code",
    subcategory: "skills",
    description: "Sincroniza config de la maquina al repo. Detecta herramientas nuevas, actualiza data.js y regenera docs.",
    install: "/sync-dotfiles",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "skill", "sync", "dotfiles"],
    url: "",
    related: [],
    why: "El inverso de setup.sh. Mantiene el repo actualizado con lo que realmente esta instalado. Single source of truth.",
  },
  // === Claude Code: Commands ===
  {
    id: "cmd-redesign-ui",
    name: "/redesign-ui",
    category: "claude-code",
    subcategory: "commands",
    description: "Analiza componentes UI y los redisena usando ui-designer y ux-designer en paralelo.",
    install: "Custom command",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "command", "ui"],
    url: "",
    related: [],
    why: "Lo construi para iterar en UI rapido. Dos agentes de disenio en paralelo y me quedo con la mejor propuesta. Ahorra horas de iteracion manual.",
  },
  {
    id: "cmd-lint",
    name: "/lint",
    category: "claude-code",
    subcategory: "commands",
    description: "Corre pre-commit suite completo: ruff, ty, isort, todos los hooks.",
    install: "Custom command",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "command", "lint", "python"],
    url: "",
    related: ["cmd-test"],
    why: "Un comando para correr todo el linting de un saque. Sin excusas para mergear codigo con warnings.",
  },
  {
    id: "cmd-test",
    name: "/test",
    category: "claude-code",
    subcategory: "commands",
    description: "Corre pytest con detalles de fallos y coverage opcional.",
    install: "Custom command",
    installMethod: "builtin",
    cost: "free",
    tags: ["claude", "command", "testing", "python"],
    url: "",
    related: ["cmd-lint"],
    why: "Wrapper de pytest que formatea output para que Claude entienda los fallos y los arregle en el siguiente paso.",
  },
  // === VS Code Extensions ===
  {
    id: "ext-claude-code",
    name: "Claude Code",
    category: "extensions",
    subcategory: "extensions",
    description: "Integracion de Claude Code en el editor.",
    install: "code --install-extension anthropic.claude-code",
    installMethod: "vscode",
    cost: "free",
    tags: ["vscode", "ai", "claude"],
    url: "",
    related: ["claude-code-cli"],
    why: "Para usar Claude Code directamente dentro del editor sin cambiar de ventana. La integracion con el diff view es excelente.",
  },
];
